/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type { CreateChatDto } from "../../models";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Send a message to the AI chat
 */
export type chatControllerCreateResponse200 = {
	data: void;
	status: 200;
};

export type chatControllerCreateResponseSuccess =
	chatControllerCreateResponse200 & {
		headers: Headers;
	};

export type chatControllerCreateResponse = chatControllerCreateResponseSuccess;

export const getChatControllerCreateUrl = () => {
	return `/chat`;
};

export const chatControllerCreate = async (
	createChatDto: CreateChatDto,
	options?: RequestInit,
): Promise<chatControllerCreateResponse> => {
	return HttpClient<chatControllerCreateResponse>(
		getChatControllerCreateUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(createChatDto),
		},
	);
};

export const getChatControllerCreateMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof chatControllerCreate>>,
		TError,
		{ data: CreateChatDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof chatControllerCreate>>,
	TError,
	{ data: CreateChatDto },
	TContext
> => {
	const mutationKey = ["chatControllerCreate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof chatControllerCreate>>,
		{ data: CreateChatDto }
	> = (props) => {
		const { data } = props ?? {};

		return chatControllerCreate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ChatControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof chatControllerCreate>>
>;
export type ChatControllerCreateMutationBody = CreateChatDto;
export type ChatControllerCreateMutationError = unknown;

/**
 * @summary Send a message to the AI chat
 */
export const useChatControllerCreate = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof chatControllerCreate>>,
			TError,
			{ data: CreateChatDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof chatControllerCreate>>,
	TError,
	{ data: CreateChatDto },
	TContext
> => {
	return useMutation(
		getChatControllerCreateMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Test the AI model connectivity
 */
export type chatControllerTestResponse200 = {
	data: void;
	status: 200;
};

export type chatControllerTestResponseSuccess =
	chatControllerTestResponse200 & {
		headers: Headers;
	};

export type chatControllerTestResponse = chatControllerTestResponseSuccess;

export const getChatControllerTestUrl = () => {
	return `/chat`;
};

export const chatControllerTest = async (
	options?: RequestInit,
): Promise<chatControllerTestResponse> => {
	return HttpClient<chatControllerTestResponse>(getChatControllerTestUrl(), {
		...options,
		method: "GET",
	});
};

export const getChatControllerTestQueryKey = () => {
	return [`/chat`] as const;
};

export const getChatControllerTestQueryOptions = <
	TData = Awaited<ReturnType<typeof chatControllerTest>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof chatControllerTest>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getChatControllerTestQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof chatControllerTest>>
	> = ({ signal }) => chatControllerTest({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof chatControllerTest>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatControllerTestQueryResult = NonNullable<
	Awaited<ReturnType<typeof chatControllerTest>>
>;
export type ChatControllerTestQueryError = unknown;

export function useChatControllerTest<
	TData = Awaited<ReturnType<typeof chatControllerTest>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof chatControllerTest>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof chatControllerTest>>,
					TError,
					Awaited<ReturnType<typeof chatControllerTest>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerTest<
	TData = Awaited<ReturnType<typeof chatControllerTest>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof chatControllerTest>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof chatControllerTest>>,
					TError,
					Awaited<ReturnType<typeof chatControllerTest>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerTest<
	TData = Awaited<ReturnType<typeof chatControllerTest>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof chatControllerTest>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Test the AI model connectivity
 */

export function useChatControllerTest<
	TData = Awaited<ReturnType<typeof chatControllerTest>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof chatControllerTest>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getChatControllerTestQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
