ARG NODE_VERSION=22.15.0
ARG PNPM_VERSION=10.11.0

# Use Node.js Alpine as base image
FROM node:${NODE_VERSION}-alpine

ARG PNPM_VERSION

# Install pnpm globally
RUN npm install -g pnpm@${PNPM_VERSION}

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Install dependencies
RUN pnpm config set store-dir /pnpm/store
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Copy source code
COPY . .

# Expose Vite port
EXPOSE 5173

# Start the development server
CMD ["pnpm", "run", "dev", "--host"]
