/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check (HEAD)
 */
export type appControllerHandleHeadRequestResponse200 = {
	data: void;
	status: 200;
};

export type appControllerHandleHeadRequestResponseSuccess =
	appControllerHandleHeadRequestResponse200 & {
		headers: Headers;
	};

export type appControllerHandleHeadRequestResponse =
	appControllerHandleHeadRequestResponseSuccess;

export const getAppControllerHandleHeadRequestUrl = () => {
	return `/`;
};

export const appControllerHandleHeadRequest = async (
	options?: RequestInit,
): Promise<appControllerHandleHeadRequestResponse> => {
	return HttpClient<appControllerHandleHeadRequestResponse>(
		getAppControllerHandleHeadRequestUrl(),
		{
			...options,
			method: "HEAD",
		},
	);
};

export const getAppControllerHandleHeadRequestMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof appControllerHandleHeadRequest>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof appControllerHandleHeadRequest>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["appControllerHandleHeadRequest"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof appControllerHandleHeadRequest>>,
		void
	> = () => {
		return appControllerHandleHeadRequest(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AppControllerHandleHeadRequestMutationResult = NonNullable<
	Awaited<ReturnType<typeof appControllerHandleHeadRequest>>
>;

export type AppControllerHandleHeadRequestMutationError = unknown;

/**
 * @summary Health check (HEAD)
 */
export const useAppControllerHandleHeadRequest = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof appControllerHandleHeadRequest>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof appControllerHandleHeadRequest>>,
	TError,
	void,
	TContext
> => {
	return useMutation(
		getAppControllerHandleHeadRequestMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Health check (GET)
 */
export type appControllerHandleGetRequestResponse200 = {
	data: void;
	status: 200;
};

export type appControllerHandleGetRequestResponseSuccess =
	appControllerHandleGetRequestResponse200 & {
		headers: Headers;
	};

export type appControllerHandleGetRequestResponse =
	appControllerHandleGetRequestResponseSuccess;

export const getAppControllerHandleGetRequestUrl = () => {
	return `/`;
};

export const appControllerHandleGetRequest = async (
	options?: RequestInit,
): Promise<appControllerHandleGetRequestResponse> => {
	return HttpClient<appControllerHandleGetRequestResponse>(
		getAppControllerHandleGetRequestUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getAppControllerHandleGetRequestQueryKey = () => {
	return [`/`] as const;
};

export const getAppControllerHandleGetRequestQueryOptions = <
	TData = Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getAppControllerHandleGetRequestQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof appControllerHandleGetRequest>>
	> = ({ signal }) =>
		appControllerHandleGetRequest({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerHandleGetRequestQueryResult = NonNullable<
	Awaited<ReturnType<typeof appControllerHandleGetRequest>>
>;
export type AppControllerHandleGetRequestQueryError = unknown;

export function useAppControllerHandleGetRequest<
	TData = Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
					TError,
					Awaited<ReturnType<typeof appControllerHandleGetRequest>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerHandleGetRequest<
	TData = Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
					TError,
					Awaited<ReturnType<typeof appControllerHandleGetRequest>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerHandleGetRequest<
	TData = Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Health check (GET)
 */

export function useAppControllerHandleGetRequest<
	TData = Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof appControllerHandleGetRequest>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getAppControllerHandleGetRequestQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
