/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Create a demo extraction run
 */
export const DemoControllerCreateRunBody = zod.object({
  "fingerprint": zod.string(),
  "extractorId": zod.string(),
  "sources": zod.array(zod.object({
  "fileId": zod.string(),
  "name": zod.string()
}))
})

/**
 * @summary Auto-classify document type
 */
export const DemoControllerClassifyBody = zod.object({
  "filename": zod.string()
})

/**
 * @summary Attach email to demo session
 */
export const DemoControllerCaptureEmailBody = zod.object({
  "fingerprint": zod.string(),
  "email": zod.string()
})

/**
 * @summary Get demo run result (public, isDemo only)
 */
export const DemoControllerGetResultParams = zod.object({
  "runId": zod.string()
})

/**
 * @summary Get demo session info by fingerprint
 */
export const DemoControllerGetSessionQueryParams = zod.object({
  "fingerprint": zod.string()
})

