/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Upload a file with user-scoped security. Files are encrypted at rest (SSE-S3) and isolated per user. Returns file ID, URL, and storage key for referencing in other CRUD operations.
 * @summary Upload a single file
 */
export const FilesControllerUploadFileBody = zod.object({
  "file": zod.instanceof(File),
  "userId": zod.string().describe('User ID (will be extracted from JWT token in production)'),
  "metadata": zod.string().optional().describe('Optional JSON metadata (e.g., {\"runId\": \"run-456\"})')
})

/**
 * Upload up to 10 files in a single request. All files are user-scoped and encrypted at rest. Returns an array of file references.
 * @summary Upload multiple files at once
 */
export const FilesControllerUploadMultipleFilesBody = zod.object({
  "files": zod.array(zod.string()).describe('Array of files to upload (max 10)'),
  "userId": zod.string().describe('User ID (will be extracted from JWT token in production)'),
  "metadata": zod.string().optional().describe('Optional JSON metadata applied to all files')
})

/**
 * Mark a list of files as completed/committed.
 * @summary Confirm files (mark as completed)
 */
export const FilesControllerConfirmFilesBody = zod.object({
  "fileIds": zod.array(zod.string()),
  "userId": zod.string()
})

/**
 * Retrieve file metadata for a specific file. User-scoped - users can only access their own files.
 * @summary Get file metadata by ID
 */
export const FilesControllerGetFileParams = zod.object({
  "id": zod.string().describe('File ID')
})

export const FilesControllerGetFileResponse = zod.object({
  "id": zod.string().optional(),
  "originalName": zod.string().optional(),
  "mimeType": zod.string().optional(),
  "size": zod.number().optional(),
  "storageKey": zod.string().optional(),
  "bucket": zod.string().optional(),
  "status": zod.string().optional(),
  "userId": zod.string().optional(),
  "metadata": zod.object({

}).optional(),
  "createdAt": zod.iso.datetime({}).optional(),
  "updatedAt": zod.iso.datetime({}).optional()
})

/**
 * Retrieve all files uploaded by the authenticated user, ordered by creation date (newest first).
 * @summary List all files for a user
 */
export const FilesControllerListFilesResponseItem = zod.object({
  "id": zod.string().optional(),
  "originalName": zod.string().optional(),
  "mimeType": zod.string().optional(),
  "size": zod.number().optional(),
  "status": zod.string().optional(),
  "createdAt": zod.iso.datetime({}).optional()
})
export const FilesControllerListFilesResponse = zod.array(FilesControllerListFilesResponseItem)

