/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Create a new user
 */
export const userControllerCreateBodyRoleDefault = `user`;

export const UserControllerCreateBody = zod.object({
  "email": zod.string(),
  "profilePicture": zod.string().optional(),
  "password": zod.string().optional(),
  "googleId": zod.string().optional(),
  "role": zod.enum(['user', 'admin'])
})

/**
 * @summary Get all users
 */
export const UserControllerFindAllQueryParams = zod.object({
  "role": zod.enum(['user', 'admin']).optional().describe('Filter users by their role'),
  "email": zod.string().optional().describe('Filter users by their email address'),
  "isEmailVerified": zod.boolean().optional().describe('Filter users by their email verification status'),
  "search": zod.string().optional().describe('Search for users by a keyword')
})

export const UserControllerFindAllResponseItem = zod.object({
  "id": zod.string().describe('Unique identifier for the user'),
  "email": zod.string().describe('User email address'),
  "profilePicture": zod.string().describe('User profile picture url'),
  "role": zod.string().describe('User role'),
  "isEmailVerified": zod.boolean().describe('Email verification status'),
  "createdAt": zod.iso.datetime({}).describe('Account creation date')
})
export const UserControllerFindAllResponse = zod.array(UserControllerFindAllResponseItem)

/**
 * @summary Get user by ID
 */
export const UserControllerFindOneParams = zod.object({
  "id": zod.string().describe('User ID')
})

export const UserControllerFindOneResponse = zod.object({
  "id": zod.string().describe('Unique identifier for the user'),
  "email": zod.string().describe('User email address'),
  "profilePicture": zod.string().describe('User profile picture url'),
  "role": zod.string().describe('User role'),
  "isEmailVerified": zod.boolean().describe('Email verification status'),
  "createdAt": zod.iso.datetime({}).describe('Account creation date')
})

/**
 * @summary Update user details
 */
export const UserControllerUpdateParams = zod.object({
  "id": zod.string().describe('User ID')
})

export const userControllerUpdateBodyRoleDefault = `user`;export const userControllerUpdateBodyIsEmailVerifiedDefault = false;

export const UserControllerUpdateBody = zod.object({
  "email": zod.string().optional(),
  "profilePicture": zod.string().optional(),
  "password": zod.string().optional(),
  "googleId": zod.string().optional(),
  "role": zod.enum(['user', 'admin']).default(userControllerUpdateBodyRoleDefault),
  "isEmailVerified": zod.boolean().default(userControllerUpdateBodyIsEmailVerifiedDefault)
})

export const UserControllerUpdateResponse = zod.object({
  "id": zod.string().describe('Unique identifier for the user'),
  "email": zod.string().describe('User email address'),
  "profilePicture": zod.string().describe('User profile picture url'),
  "role": zod.string().describe('User role'),
  "isEmailVerified": zod.boolean().describe('Email verification status'),
  "createdAt": zod.iso.datetime({}).describe('Account creation date')
})

/**
 * @summary Delete a user
 */
export const UserControllerRemoveParams = zod.object({
  "id": zod.string().describe('User ID')
})

