/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ExtractorsIndexRouteImport } from './routes/extractors/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AutorunsIndexRouteImport } from './routes/autoruns/index'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsInstanceRouteImport } from './routes/settings/instance'
import { Route as SettingsExtractionRouteImport } from './routes/settings/extraction'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as RunsNewRouteImport } from './routes/runs/new'
import { Route as RunsIdRouteImport } from './routes/runs/$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ExtractorsNewRouteImport } from './routes/extractors/new'
import { Route as ExtractorsIdRouteImport } from './routes/extractors/$id'
import { Route as AutorunsNewRouteImport } from './routes/autoruns/new'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as RunsReviewIdRouteImport } from './routes/runs/review.$id'
import { Route as ExtractorsEditIdRouteImport } from './routes/extractors/edit.$id'
import { Route as DemoResultRunIdRouteImport } from './routes/demo/result.$runId'
import { Route as AutorunsRunsIdRouteImport } from './routes/autoruns/runs.$id'
import { Route as AutorunsEditIdRouteImport } from './routes/autoruns/edit.$id'
import { Route as AutorunsBuilderIdRouteImport } from './routes/autoruns/builder.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsIndexRoute = ExtractorsIndexRouteImport.update({
  id: '/extractors/',
  path: '/extractors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorunsIndexRoute = AutorunsIndexRouteImport.update({
  id: '/autoruns/',
  path: '/autoruns/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsInstanceRoute = SettingsInstanceRouteImport.update({
  id: '/instance',
  path: '/instance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtractionRoute = SettingsExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const RunsNewRoute = RunsNewRouteImport.update({
  id: '/runs/new',
  path: '/runs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsNewRoute = ExtractorsNewRouteImport.update({
  id: '/extractors/new',
  path: '/extractors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsIdRoute = ExtractorsIdRouteImport.update({
  id: '/extractors/$id',
  path: '/extractors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorunsNewRoute = AutorunsNewRouteImport.update({
  id: '/autoruns/new',
  path: '/autoruns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsReviewIdRoute = RunsReviewIdRouteImport.update({
  id: '/runs/review/$id',
  path: '/runs/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsEditIdRoute = ExtractorsEditIdRouteImport.update({
  id: '/extractors/edit/$id',
  path: '/extractors/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoResultRunIdRoute = DemoResultRunIdRouteImport.update({
  id: '/result/$runId',
  path: '/result/$runId',
  getParentRoute: () => DemoRoute,
} as any)
const AutorunsRunsIdRoute = AutorunsRunsIdRouteImport.update({
  id: '/autoruns/runs/$id',
  path: '/autoruns/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorunsEditIdRoute = AutorunsEditIdRouteImport.update({
  id: '/autoruns/edit/$id',
  path: '/autoruns/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorunsBuilderIdRoute = AutorunsBuilderIdRouteImport.update({
  id: '/autoruns/builder/$id',
  path: '/autoruns/builder/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/autoruns/new': typeof AutorunsNewRoute
  '/extractors/$id': typeof ExtractorsIdRoute
  '/extractors/new': typeof ExtractorsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/new': typeof RunsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/extraction': typeof SettingsExtractionRoute
  '/settings/instance': typeof SettingsInstanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/autoruns/': typeof AutorunsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/extractors/': typeof ExtractorsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/autoruns/builder/$id': typeof AutorunsBuilderIdRoute
  '/autoruns/edit/$id': typeof AutorunsEditIdRoute
  '/autoruns/runs/$id': typeof AutorunsRunsIdRoute
  '/demo/result/$runId': typeof DemoResultRunIdRoute
  '/extractors/edit/$id': typeof ExtractorsEditIdRoute
  '/runs/review/$id': typeof RunsReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/autoruns/new': typeof AutorunsNewRoute
  '/extractors/$id': typeof ExtractorsIdRoute
  '/extractors/new': typeof ExtractorsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/new': typeof RunsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/extraction': typeof SettingsExtractionRoute
  '/settings/instance': typeof SettingsInstanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/autoruns': typeof AutorunsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/demo': typeof DemoIndexRoute
  '/extractors': typeof ExtractorsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/autoruns/builder/$id': typeof AutorunsBuilderIdRoute
  '/autoruns/edit/$id': typeof AutorunsEditIdRoute
  '/autoruns/runs/$id': typeof AutorunsRunsIdRoute
  '/demo/result/$runId': typeof DemoResultRunIdRoute
  '/extractors/edit/$id': typeof ExtractorsEditIdRoute
  '/runs/review/$id': typeof RunsReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/autoruns/new': typeof AutorunsNewRoute
  '/extractors/$id': typeof ExtractorsIdRoute
  '/extractors/new': typeof ExtractorsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/new': typeof RunsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/extraction': typeof SettingsExtractionRoute
  '/settings/instance': typeof SettingsInstanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/autoruns/': typeof AutorunsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/extractors/': typeof ExtractorsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/autoruns/builder/$id': typeof AutorunsBuilderIdRoute
  '/autoruns/edit/$id': typeof AutorunsEditIdRoute
  '/autoruns/runs/$id': typeof AutorunsRunsIdRoute
  '/demo/result/$runId': typeof DemoResultRunIdRoute
  '/extractors/edit/$id': typeof ExtractorsEditIdRoute
  '/runs/review/$id': typeof RunsReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/auth/callback'
    | '/auth/verify'
    | '/autoruns/new'
    | '/extractors/$id'
    | '/extractors/new'
    | '/invite/$token'
    | '/runs/$id'
    | '/runs/new'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/extraction'
    | '/settings/instance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/autoruns/'
    | '/dashboard/'
    | '/demo/'
    | '/extractors/'
    | '/runs/'
    | '/settings/'
    | '/autoruns/builder/$id'
    | '/autoruns/edit/$id'
    | '/autoruns/runs/$id'
    | '/demo/result/$runId'
    | '/extractors/edit/$id'
    | '/runs/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/signup'
    | '/auth/callback'
    | '/auth/verify'
    | '/autoruns/new'
    | '/extractors/$id'
    | '/extractors/new'
    | '/invite/$token'
    | '/runs/$id'
    | '/runs/new'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/extraction'
    | '/settings/instance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/autoruns'
    | '/dashboard'
    | '/demo'
    | '/extractors'
    | '/runs'
    | '/settings'
    | '/autoruns/builder/$id'
    | '/autoruns/edit/$id'
    | '/autoruns/runs/$id'
    | '/demo/result/$runId'
    | '/extractors/edit/$id'
    | '/runs/review/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/auth/callback'
    | '/auth/verify'
    | '/autoruns/new'
    | '/extractors/$id'
    | '/extractors/new'
    | '/invite/$token'
    | '/runs/$id'
    | '/runs/new'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/extraction'
    | '/settings/instance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/autoruns/'
    | '/dashboard/'
    | '/demo/'
    | '/extractors/'
    | '/runs/'
    | '/settings/'
    | '/autoruns/builder/$id'
    | '/autoruns/edit/$id'
    | '/autoruns/runs/$id'
    | '/demo/result/$runId'
    | '/extractors/edit/$id'
    | '/runs/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AutorunsNewRoute: typeof AutorunsNewRoute
  ExtractorsIdRoute: typeof ExtractorsIdRoute
  ExtractorsNewRoute: typeof ExtractorsNewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RunsIdRoute: typeof RunsIdRoute
  RunsNewRoute: typeof RunsNewRoute
  AutorunsIndexRoute: typeof AutorunsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ExtractorsIndexRoute: typeof ExtractorsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  AutorunsBuilderIdRoute: typeof AutorunsBuilderIdRoute
  AutorunsEditIdRoute: typeof AutorunsEditIdRoute
  AutorunsRunsIdRoute: typeof AutorunsRunsIdRoute
  ExtractorsEditIdRoute: typeof ExtractorsEditIdRoute
  RunsReviewIdRoute: typeof RunsReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors/': {
      id: '/extractors/'
      path: '/extractors'
      fullPath: '/extractors/'
      preLoaderRoute: typeof ExtractorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoruns/': {
      id: '/autoruns/'
      path: '/autoruns'
      fullPath: '/autoruns/'
      preLoaderRoute: typeof AutorunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/instance': {
      id: '/settings/instance'
      path: '/instance'
      fullPath: '/settings/instance'
      preLoaderRoute: typeof SettingsInstanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extraction': {
      id: '/settings/extraction'
      path: '/extraction'
      fullPath: '/settings/extraction'
      preLoaderRoute: typeof SettingsExtractionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/runs/new': {
      id: '/runs/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof RunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors/new': {
      id: '/extractors/new'
      path: '/extractors/new'
      fullPath: '/extractors/new'
      preLoaderRoute: typeof ExtractorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors/$id': {
      id: '/extractors/$id'
      path: '/extractors/$id'
      fullPath: '/extractors/$id'
      preLoaderRoute: typeof ExtractorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoruns/new': {
      id: '/autoruns/new'
      path: '/autoruns/new'
      fullPath: '/autoruns/new'
      preLoaderRoute: typeof AutorunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/review/$id': {
      id: '/runs/review/$id'
      path: '/runs/review/$id'
      fullPath: '/runs/review/$id'
      preLoaderRoute: typeof RunsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors/edit/$id': {
      id: '/extractors/edit/$id'
      path: '/extractors/edit/$id'
      fullPath: '/extractors/edit/$id'
      preLoaderRoute: typeof ExtractorsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/result/$runId': {
      id: '/demo/result/$runId'
      path: '/result/$runId'
      fullPath: '/demo/result/$runId'
      preLoaderRoute: typeof DemoResultRunIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/autoruns/runs/$id': {
      id: '/autoruns/runs/$id'
      path: '/autoruns/runs/$id'
      fullPath: '/autoruns/runs/$id'
      preLoaderRoute: typeof AutorunsRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoruns/edit/$id': {
      id: '/autoruns/edit/$id'
      path: '/autoruns/edit/$id'
      fullPath: '/autoruns/edit/$id'
      preLoaderRoute: typeof AutorunsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoruns/builder/$id': {
      id: '/autoruns/builder/$id'
      path: '/autoruns/builder/$id'
      fullPath: '/autoruns/builder/$id'
      preLoaderRoute: typeof AutorunsBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DemoRouteChildren {
  DemoIndexRoute: typeof DemoIndexRoute
  DemoResultRunIdRoute: typeof DemoResultRunIdRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoIndexRoute: DemoIndexRoute,
  DemoResultRunIdRoute: DemoResultRunIdRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface SettingsRouteChildren {
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsExtractionRoute: typeof SettingsExtractionRoute
  SettingsInstanceRoute: typeof SettingsInstanceRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsExtractionRoute: SettingsExtractionRoute,
  SettingsInstanceRoute: SettingsInstanceRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AutorunsNewRoute: AutorunsNewRoute,
  ExtractorsIdRoute: ExtractorsIdRoute,
  ExtractorsNewRoute: ExtractorsNewRoute,
  InviteTokenRoute: InviteTokenRoute,
  RunsIdRoute: RunsIdRoute,
  RunsNewRoute: RunsNewRoute,
  AutorunsIndexRoute: AutorunsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ExtractorsIndexRoute: ExtractorsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  AutorunsBuilderIdRoute: AutorunsBuilderIdRoute,
  AutorunsEditIdRoute: AutorunsEditIdRoute,
  AutorunsRunsIdRoute: AutorunsRunsIdRoute,
  ExtractorsEditIdRoute: ExtractorsEditIdRoute,
  RunsReviewIdRoute: RunsReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
