/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ExtractorsIndexRouteImport } from './routes/extractors/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AutorunsIndexRouteImport } from './routes/autoruns/index'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsExtractionRouteImport } from './routes/settings/extraction'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as RunsNewRouteImport } from './routes/runs/new'
import { Route as RunsIdRouteImport } from './routes/runs/$id'
import { Route as ExtractorsNewRouteImport } from './routes/extractors/new'
import { Route as ExtractorsIdRouteImport } from './routes/extractors/$id'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoAiStructuredRouteImport } from './routes/demo/ai-structured'
import { Route as DemoAiImageRouteImport } from './routes/demo/ai-image'
import { Route as DemoAiChatRouteImport } from './routes/demo/ai-chat'
import { Route as AutorunsNewRouteImport } from './routes/autoruns/new'
import { Route as DemoGuitarsIndexRouteImport } from './routes/demo/guitars/index'
import { Route as RunsReviewIdRouteImport } from './routes/runs/review.$id'
import { Route as ExtractorsEditIdRouteImport } from './routes/extractors/edit.$id'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as DemoGuitarsGuitarIdRouteImport } from './routes/demo/guitars/$guitarId'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AutorunsRunsIdRouteImport } from './routes/autoruns/runs.$id'
import { Route as AutorunsEditIdRouteImport } from './routes/autoruns/edit.$id'
import { Route as AutorunsBuilderIdRouteImport } from './routes/autoruns/builder.$id'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as DemoApiAiTtsRouteImport } from './routes/demo/api.ai.tts'
import { Route as DemoApiAiTranscriptionRouteImport } from './routes/demo/api.ai.transcription'
import { Route as DemoApiAiStructuredRouteImport } from './routes/demo/api.ai.structured'
import { Route as DemoApiAiImageRouteImport } from './routes/demo/api.ai.image'
import { Route as DemoApiAiChatRouteImport } from './routes/demo/api.ai.chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsIndexRoute = ExtractorsIndexRouteImport.update({
  id: '/extractors/',
  path: '/extractors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorunsIndexRoute = AutorunsIndexRouteImport.update({
  id: '/autoruns/',
  path: '/autoruns/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtractionRoute = SettingsExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const RunsNewRoute = RunsNewRouteImport.update({
  id: '/runs/new',
  path: '/runs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsNewRoute = ExtractorsNewRouteImport.update({
  id: '/extractors/new',
  path: '/extractors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsIdRoute = ExtractorsIdRouteImport.update({
  id: '/extractors/$id',
  path: '/extractors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/tanstack-query',
  path: '/tanstack-query',
  getParentRoute: () => DemoRoute,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAiStructuredRoute = DemoAiStructuredRouteImport.update({
  id: '/ai-structured',
  path: '/ai-structured',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAiImageRoute = DemoAiImageRouteImport.update({
  id: '/ai-image',
  path: '/ai-image',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAiChatRoute = DemoAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => DemoRoute,
} as any)
const AutorunsNewRoute = AutorunsNewRouteImport.update({
  id: '/autoruns/new',
  path: '/autoruns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsIndexRoute = DemoGuitarsIndexRouteImport.update({
  id: '/guitars/',
  path: '/guitars/',
  getParentRoute: () => DemoRoute,
} as any)
const RunsReviewIdRoute = RunsReviewIdRouteImport.update({
  id: '/runs/review/$id',
  path: '/runs/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsEditIdRoute = ExtractorsEditIdRouteImport.update({
  id: '/extractors/edit/$id',
  path: '/extractors/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/start/server-funcs',
  path: '/start/server-funcs',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/start/api-request',
  path: '/start/api-request',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/sentry/testing',
  path: '/sentry/testing',
  getParentRoute: () => DemoRoute,
} as any)
const DemoGuitarsGuitarIdRoute = DemoGuitarsGuitarIdRouteImport.update({
  id: '/guitars/$guitarId',
  path: '/guitars/$guitarId',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/api/tq-todos',
  path: '/api/tq-todos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/api/names',
  path: '/api/names',
  getParentRoute: () => DemoRoute,
} as any)
const AutorunsRunsIdRoute = AutorunsRunsIdRouteImport.update({
  id: '/autoruns/runs/$id',
  path: '/autoruns/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorunsEditIdRoute = AutorunsEditIdRouteImport.update({
  id: '/autoruns/edit/$id',
  path: '/autoruns/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorunsBuilderIdRoute = AutorunsBuilderIdRouteImport.update({
  id: '/autoruns/builder/$id',
  path: '/autoruns/builder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/start/ssr/',
  path: '/start/ssr/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/start/ssr/spa-mode',
  path: '/start/ssr/spa-mode',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/start/ssr/full-ssr',
  path: '/start/ssr/full-ssr',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/start/ssr/data-only',
  path: '/start/ssr/data-only',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiAiTtsRoute = DemoApiAiTtsRouteImport.update({
  id: '/api/ai/tts',
  path: '/api/ai/tts',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiAiTranscriptionRoute = DemoApiAiTranscriptionRouteImport.update({
  id: '/api/ai/transcription',
  path: '/api/ai/transcription',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiAiStructuredRoute = DemoApiAiStructuredRouteImport.update({
  id: '/api/ai/structured',
  path: '/api/ai/structured',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiAiImageRoute = DemoApiAiImageRouteImport.update({
  id: '/api/ai/image',
  path: '/api/ai/image',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiAiChatRoute = DemoApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/autoruns/new': typeof AutorunsNewRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/extractors/$id': typeof ExtractorsIdRoute
  '/extractors/new': typeof ExtractorsNewRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/new': typeof RunsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/extraction': typeof SettingsExtractionRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/autoruns/': typeof AutorunsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/extractors/': typeof ExtractorsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/autoruns/builder/$id': typeof AutorunsBuilderIdRoute
  '/autoruns/edit/$id': typeof AutorunsEditIdRoute
  '/autoruns/runs/$id': typeof AutorunsRunsIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/extractors/edit/$id': typeof ExtractorsEditIdRoute
  '/runs/review/$id': typeof RunsReviewIdRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/autoruns/new': typeof AutorunsNewRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/extractors/$id': typeof ExtractorsIdRoute
  '/extractors/new': typeof ExtractorsNewRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/new': typeof RunsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/extraction': typeof SettingsExtractionRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/autoruns': typeof AutorunsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/extractors': typeof ExtractorsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/autoruns/builder/$id': typeof AutorunsBuilderIdRoute
  '/autoruns/edit/$id': typeof AutorunsEditIdRoute
  '/autoruns/runs/$id': typeof AutorunsRunsIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/extractors/edit/$id': typeof ExtractorsEditIdRoute
  '/runs/review/$id': typeof RunsReviewIdRoute
  '/demo/guitars': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/autoruns/new': typeof AutorunsNewRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/extractors/$id': typeof ExtractorsIdRoute
  '/extractors/new': typeof ExtractorsNewRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/new': typeof RunsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/extraction': typeof SettingsExtractionRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/autoruns/': typeof AutorunsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/extractors/': typeof ExtractorsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/autoruns/builder/$id': typeof AutorunsBuilderIdRoute
  '/autoruns/edit/$id': typeof AutorunsEditIdRoute
  '/autoruns/runs/$id': typeof AutorunsRunsIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/extractors/edit/$id': typeof ExtractorsEditIdRoute
  '/runs/review/$id': typeof RunsReviewIdRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/settings'
    | '/signup'
    | '/autoruns/new'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/extractors/$id'
    | '/extractors/new'
    | '/runs/$id'
    | '/runs/new'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/extraction'
    | '/settings/notifications'
    | '/settings/profile'
    | '/autoruns/'
    | '/dashboard/'
    | '/extractors/'
    | '/runs/'
    | '/settings/'
    | '/autoruns/builder/$id'
    | '/autoruns/edit/$id'
    | '/autoruns/runs/$id'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/guitars/$guitarId'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/extractors/edit/$id'
    | '/runs/review/$id'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/signup'
    | '/autoruns/new'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/extractors/$id'
    | '/extractors/new'
    | '/runs/$id'
    | '/runs/new'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/extraction'
    | '/settings/notifications'
    | '/settings/profile'
    | '/autoruns'
    | '/dashboard'
    | '/extractors'
    | '/runs'
    | '/settings'
    | '/autoruns/builder/$id'
    | '/autoruns/edit/$id'
    | '/autoruns/runs/$id'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/guitars/$guitarId'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/extractors/edit/$id'
    | '/runs/review/$id'
    | '/demo/guitars'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/settings'
    | '/signup'
    | '/autoruns/new'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/extractors/$id'
    | '/extractors/new'
    | '/runs/$id'
    | '/runs/new'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/extraction'
    | '/settings/notifications'
    | '/settings/profile'
    | '/autoruns/'
    | '/dashboard/'
    | '/extractors/'
    | '/runs/'
    | '/settings/'
    | '/autoruns/builder/$id'
    | '/autoruns/edit/$id'
    | '/autoruns/runs/$id'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/guitars/$guitarId'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/extractors/edit/$id'
    | '/runs/review/$id'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  AutorunsNewRoute: typeof AutorunsNewRoute
  ExtractorsIdRoute: typeof ExtractorsIdRoute
  ExtractorsNewRoute: typeof ExtractorsNewRoute
  RunsIdRoute: typeof RunsIdRoute
  RunsNewRoute: typeof RunsNewRoute
  AutorunsIndexRoute: typeof AutorunsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ExtractorsIndexRoute: typeof ExtractorsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  AutorunsBuilderIdRoute: typeof AutorunsBuilderIdRoute
  AutorunsEditIdRoute: typeof AutorunsEditIdRoute
  AutorunsRunsIdRoute: typeof AutorunsRunsIdRoute
  ExtractorsEditIdRoute: typeof ExtractorsEditIdRoute
  RunsReviewIdRoute: typeof RunsReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors/': {
      id: '/extractors/'
      path: '/extractors'
      fullPath: '/extractors/'
      preLoaderRoute: typeof ExtractorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoruns/': {
      id: '/autoruns/'
      path: '/autoruns'
      fullPath: '/autoruns/'
      preLoaderRoute: typeof AutorunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extraction': {
      id: '/settings/extraction'
      path: '/extraction'
      fullPath: '/settings/extraction'
      preLoaderRoute: typeof SettingsExtractionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/runs/new': {
      id: '/runs/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof RunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors/new': {
      id: '/extractors/new'
      path: '/extractors/new'
      fullPath: '/extractors/new'
      preLoaderRoute: typeof ExtractorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors/$id': {
      id: '/extractors/$id'
      path: '/extractors/$id'
      fullPath: '/extractors/$id'
      preLoaderRoute: typeof ExtractorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ai-structured': {
      id: '/demo/ai-structured'
      path: '/ai-structured'
      fullPath: '/demo/ai-structured'
      preLoaderRoute: typeof DemoAiStructuredRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ai-image': {
      id: '/demo/ai-image'
      path: '/ai-image'
      fullPath: '/demo/ai-image'
      preLoaderRoute: typeof DemoAiImageRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ai-chat': {
      id: '/demo/ai-chat'
      path: '/ai-chat'
      fullPath: '/demo/ai-chat'
      preLoaderRoute: typeof DemoAiChatRouteImport
      parentRoute: typeof DemoRoute
    }
    '/autoruns/new': {
      id: '/autoruns/new'
      path: '/autoruns/new'
      fullPath: '/autoruns/new'
      preLoaderRoute: typeof AutorunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/': {
      id: '/demo/guitars/'
      path: '/guitars'
      fullPath: '/demo/guitars/'
      preLoaderRoute: typeof DemoGuitarsIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/runs/review/$id': {
      id: '/runs/review/$id'
      path: '/runs/review/$id'
      fullPath: '/runs/review/$id'
      preLoaderRoute: typeof RunsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors/edit/$id': {
      id: '/extractors/edit/$id'
      path: '/extractors/edit/$id'
      fullPath: '/extractors/edit/$id'
      preLoaderRoute: typeof ExtractorsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/guitars/$guitarId': {
      id: '/demo/guitars/$guitarId'
      path: '/guitars/$guitarId'
      fullPath: '/demo/guitars/$guitarId'
      preLoaderRoute: typeof DemoGuitarsGuitarIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/autoruns/runs/$id': {
      id: '/autoruns/runs/$id'
      path: '/autoruns/runs/$id'
      fullPath: '/autoruns/runs/$id'
      preLoaderRoute: typeof AutorunsRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoruns/edit/$id': {
      id: '/autoruns/edit/$id'
      path: '/autoruns/edit/$id'
      fullPath: '/autoruns/edit/$id'
      preLoaderRoute: typeof AutorunsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoruns/builder/$id': {
      id: '/autoruns/builder/$id'
      path: '/autoruns/builder/$id'
      fullPath: '/autoruns/builder/$id'
      preLoaderRoute: typeof AutorunsBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/ai/tts': {
      id: '/demo/api/ai/tts'
      path: '/api/ai/tts'
      fullPath: '/demo/api/ai/tts'
      preLoaderRoute: typeof DemoApiAiTtsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/ai/transcription': {
      id: '/demo/api/ai/transcription'
      path: '/api/ai/transcription'
      fullPath: '/demo/api/ai/transcription'
      preLoaderRoute: typeof DemoApiAiTranscriptionRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/ai/structured': {
      id: '/demo/api/ai/structured'
      path: '/api/ai/structured'
      fullPath: '/demo/api/ai/structured'
      preLoaderRoute: typeof DemoApiAiStructuredRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/ai/image': {
      id: '/demo/api/ai/image'
      path: '/api/ai/image'
      fullPath: '/demo/api/ai/image'
      preLoaderRoute: typeof DemoApiAiImageRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/ai/chat': {
      id: '/demo/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/demo/api/ai/chat'
      preLoaderRoute: typeof DemoApiAiChatRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoAiChatRoute: typeof DemoAiChatRoute
  DemoAiImageRoute: typeof DemoAiImageRoute
  DemoAiStructuredRoute: typeof DemoAiStructuredRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoGuitarsGuitarIdRoute: typeof DemoGuitarsGuitarIdRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoGuitarsIndexRoute: typeof DemoGuitarsIndexRoute
  DemoApiAiChatRoute: typeof DemoApiAiChatRoute
  DemoApiAiImageRoute: typeof DemoApiAiImageRoute
  DemoApiAiStructuredRoute: typeof DemoApiAiStructuredRoute
  DemoApiAiTranscriptionRoute: typeof DemoApiAiTranscriptionRoute
  DemoApiAiTtsRoute: typeof DemoApiAiTtsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAiChatRoute: DemoAiChatRoute,
  DemoAiImageRoute: DemoAiImageRoute,
  DemoAiStructuredRoute: DemoAiStructuredRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoGuitarsGuitarIdRoute: DemoGuitarsGuitarIdRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoGuitarsIndexRoute: DemoGuitarsIndexRoute,
  DemoApiAiChatRoute: DemoApiAiChatRoute,
  DemoApiAiImageRoute: DemoApiAiImageRoute,
  DemoApiAiStructuredRoute: DemoApiAiStructuredRoute,
  DemoApiAiTranscriptionRoute: DemoApiAiTranscriptionRoute,
  DemoApiAiTtsRoute: DemoApiAiTtsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface SettingsRouteChildren {
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsExtractionRoute: typeof SettingsExtractionRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsExtractionRoute: SettingsExtractionRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  AutorunsNewRoute: AutorunsNewRoute,
  ExtractorsIdRoute: ExtractorsIdRoute,
  ExtractorsNewRoute: ExtractorsNewRoute,
  RunsIdRoute: RunsIdRoute,
  RunsNewRoute: RunsNewRoute,
  AutorunsIndexRoute: AutorunsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ExtractorsIndexRoute: ExtractorsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  AutorunsBuilderIdRoute: AutorunsBuilderIdRoute,
  AutorunsEditIdRoute: AutorunsEditIdRoute,
  AutorunsRunsIdRoute: AutorunsRunsIdRoute,
  ExtractorsEditIdRoute: ExtractorsEditIdRoute,
  RunsReviewIdRoute: RunsReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
