/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	AcceptInviteDto,
	CreateInviteDto,
	InviteControllerFindAllParams,
} from "../../models";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type inviteControllerCreateResponse201 = {
	data: void;
	status: 201;
};

export type inviteControllerCreateResponseSuccess =
	inviteControllerCreateResponse201 & {
		headers: Headers;
	};

export type inviteControllerCreateResponse =
	inviteControllerCreateResponseSuccess;

export const getInviteControllerCreateUrl = () => {
	return `/invites`;
};

export const inviteControllerCreate = async (
	createInviteDto: CreateInviteDto,
	options?: RequestInit,
): Promise<inviteControllerCreateResponse> => {
	return HttpClient<inviteControllerCreateResponse>(
		getInviteControllerCreateUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(createInviteDto),
		},
	);
};

export const getInviteControllerCreateMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inviteControllerCreate>>,
		TError,
		{ data: CreateInviteDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inviteControllerCreate>>,
	TError,
	{ data: CreateInviteDto },
	TContext
> => {
	const mutationKey = ["inviteControllerCreate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inviteControllerCreate>>,
		{ data: CreateInviteDto }
	> = (props) => {
		const { data } = props ?? {};

		return inviteControllerCreate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type InviteControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof inviteControllerCreate>>
>;
export type InviteControllerCreateMutationBody = CreateInviteDto;
export type InviteControllerCreateMutationError = unknown;

export const useInviteControllerCreate = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof inviteControllerCreate>>,
			TError,
			{ data: CreateInviteDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof inviteControllerCreate>>,
	TError,
	{ data: CreateInviteDto },
	TContext
> => {
	return useMutation(
		getInviteControllerCreateMutationOptions(options),
		queryClient,
	);
};
export type inviteControllerFindAllResponse200 = {
	data: void;
	status: 200;
};

export type inviteControllerFindAllResponseSuccess =
	inviteControllerFindAllResponse200 & {
		headers: Headers;
	};

export type inviteControllerFindAllResponse =
	inviteControllerFindAllResponseSuccess;

export const getInviteControllerFindAllUrl = (
	params: InviteControllerFindAllParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/invites?${stringifiedParams}`
		: `/invites`;
};

export const inviteControllerFindAll = async (
	params: InviteControllerFindAllParams,
	options?: RequestInit,
): Promise<inviteControllerFindAllResponse> => {
	return HttpClient<inviteControllerFindAllResponse>(
		getInviteControllerFindAllUrl(params),
		{
			...options,
			method: "GET",
		},
	);
};

export const getInviteControllerFindAllQueryKey = (
	params?: InviteControllerFindAllParams,
) => {
	return [`/invites`, ...(params ? [params] : [])] as const;
};

export const getInviteControllerFindAllQueryOptions = <
	TData = Awaited<ReturnType<typeof inviteControllerFindAll>>,
	TError = unknown,
>(
	params: InviteControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getInviteControllerFindAllQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof inviteControllerFindAll>>
	> = ({ signal }) =>
		inviteControllerFindAll(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof inviteControllerFindAll>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InviteControllerFindAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof inviteControllerFindAll>>
>;
export type InviteControllerFindAllQueryError = unknown;

export function useInviteControllerFindAll<
	TData = Awaited<ReturnType<typeof inviteControllerFindAll>>,
	TError = unknown,
>(
	params: InviteControllerFindAllParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerFindAll>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof inviteControllerFindAll>>,
					TError,
					Awaited<ReturnType<typeof inviteControllerFindAll>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInviteControllerFindAll<
	TData = Awaited<ReturnType<typeof inviteControllerFindAll>>,
	TError = unknown,
>(
	params: InviteControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerFindAll>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof inviteControllerFindAll>>,
					TError,
					Awaited<ReturnType<typeof inviteControllerFindAll>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInviteControllerFindAll<
	TData = Awaited<ReturnType<typeof inviteControllerFindAll>>,
	TError = unknown,
>(
	params: InviteControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useInviteControllerFindAll<
	TData = Awaited<ReturnType<typeof inviteControllerFindAll>>,
	TError = unknown,
>(
	params: InviteControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getInviteControllerFindAllQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type inviteControllerValidateResponse200 = {
	data: void;
	status: 200;
};

export type inviteControllerValidateResponseSuccess =
	inviteControllerValidateResponse200 & {
		headers: Headers;
	};

export type inviteControllerValidateResponse =
	inviteControllerValidateResponseSuccess;

export const getInviteControllerValidateUrl = (token: string) => {
	return `/invites/${token}/validate`;
};

export const inviteControllerValidate = async (
	token: string,
	options?: RequestInit,
): Promise<inviteControllerValidateResponse> => {
	return HttpClient<inviteControllerValidateResponse>(
		getInviteControllerValidateUrl(token),
		{
			...options,
			method: "GET",
		},
	);
};

export const getInviteControllerValidateQueryKey = (token: string) => {
	return [`/invites/${token}/validate`] as const;
};

export const getInviteControllerValidateQueryOptions = <
	TData = Awaited<ReturnType<typeof inviteControllerValidate>>,
	TError = unknown,
>(
	token: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerValidate>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getInviteControllerValidateQueryKey(token);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof inviteControllerValidate>>
	> = ({ signal }) =>
		inviteControllerValidate(token, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!token,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof inviteControllerValidate>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InviteControllerValidateQueryResult = NonNullable<
	Awaited<ReturnType<typeof inviteControllerValidate>>
>;
export type InviteControllerValidateQueryError = unknown;

export function useInviteControllerValidate<
	TData = Awaited<ReturnType<typeof inviteControllerValidate>>,
	TError = unknown,
>(
	token: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerValidate>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof inviteControllerValidate>>,
					TError,
					Awaited<ReturnType<typeof inviteControllerValidate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInviteControllerValidate<
	TData = Awaited<ReturnType<typeof inviteControllerValidate>>,
	TError = unknown,
>(
	token: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerValidate>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof inviteControllerValidate>>,
					TError,
					Awaited<ReturnType<typeof inviteControllerValidate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInviteControllerValidate<
	TData = Awaited<ReturnType<typeof inviteControllerValidate>>,
	TError = unknown,
>(
	token: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerValidate>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useInviteControllerValidate<
	TData = Awaited<ReturnType<typeof inviteControllerValidate>>,
	TError = unknown,
>(
	token: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof inviteControllerValidate>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getInviteControllerValidateQueryOptions(token, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type inviteControllerAcceptResponse201 = {
	data: void;
	status: 201;
};

export type inviteControllerAcceptResponseSuccess =
	inviteControllerAcceptResponse201 & {
		headers: Headers;
	};

export type inviteControllerAcceptResponse =
	inviteControllerAcceptResponseSuccess;

export const getInviteControllerAcceptUrl = (token: string) => {
	return `/invites/${token}/accept`;
};

export const inviteControllerAccept = async (
	token: string,
	acceptInviteDto: AcceptInviteDto,
	options?: RequestInit,
): Promise<inviteControllerAcceptResponse> => {
	return HttpClient<inviteControllerAcceptResponse>(
		getInviteControllerAcceptUrl(token),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(acceptInviteDto),
		},
	);
};

export const getInviteControllerAcceptMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inviteControllerAccept>>,
		TError,
		{ token: string; data: AcceptInviteDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inviteControllerAccept>>,
	TError,
	{ token: string; data: AcceptInviteDto },
	TContext
> => {
	const mutationKey = ["inviteControllerAccept"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inviteControllerAccept>>,
		{ token: string; data: AcceptInviteDto }
	> = (props) => {
		const { token, data } = props ?? {};

		return inviteControllerAccept(token, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type InviteControllerAcceptMutationResult = NonNullable<
	Awaited<ReturnType<typeof inviteControllerAccept>>
>;
export type InviteControllerAcceptMutationBody = AcceptInviteDto;
export type InviteControllerAcceptMutationError = unknown;

export const useInviteControllerAccept = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof inviteControllerAccept>>,
			TError,
			{ token: string; data: AcceptInviteDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof inviteControllerAccept>>,
	TError,
	{ token: string; data: AcceptInviteDto },
	TContext
> => {
	return useMutation(
		getInviteControllerAcceptMutationOptions(options),
		queryClient,
	);
};
export type inviteControllerRevokeResponse200 = {
	data: void;
	status: 200;
};

export type inviteControllerRevokeResponseSuccess =
	inviteControllerRevokeResponse200 & {
		headers: Headers;
	};

export type inviteControllerRevokeResponse =
	inviteControllerRevokeResponseSuccess;

export const getInviteControllerRevokeUrl = (id: string) => {
	return `/invites/${id}`;
};

export const inviteControllerRevoke = async (
	id: string,
	options?: RequestInit,
): Promise<inviteControllerRevokeResponse> => {
	return HttpClient<inviteControllerRevokeResponse>(
		getInviteControllerRevokeUrl(id),
		{
			...options,
			method: "DELETE",
		},
	);
};

export const getInviteControllerRevokeMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof inviteControllerRevoke>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof inviteControllerRevoke>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["inviteControllerRevoke"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof inviteControllerRevoke>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return inviteControllerRevoke(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type InviteControllerRevokeMutationResult = NonNullable<
	Awaited<ReturnType<typeof inviteControllerRevoke>>
>;

export type InviteControllerRevokeMutationError = unknown;

export const useInviteControllerRevoke = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof inviteControllerRevoke>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof inviteControllerRevoke>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getInviteControllerRevokeMutationOptions(options),
		queryClient,
	);
};
