/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Register a new user
 */
export const AuthControllerSignUpBody = zod.object({
  "email": zod.string().describe('The email address of the user'),
  "password": zod.string().describe('The password of the user. Must be at least 8 characters long.')
})

/**
 * @summary Authenticate user
 */
export const AuthControllerLoginBody = zod.object({
  "email": zod.string().describe('The email address of the user'),
  "password": zod.string().describe('The password of the user')
})

export const AuthControllerLoginResponse = zod.object({
  "accessToken": zod.string(),
  "refreshToken": zod.string(),
  "user": zod.object({
  "id": zod.string().describe('Unique identifier for the user'),
  "email": zod.string().describe('User email address'),
  "profilePicture": zod.string().describe('User profile picture url'),
  "role": zod.string().describe('User role'),
  "isEmailVerified": zod.boolean().describe('Email verification status'),
  "createdAt": zod.iso.datetime({}).describe('Account creation date')
})
})

/**
 * @summary Refresh access token
 */
export const AuthControllerRefreshTokenBody = zod.object({
  "refreshToken": zod.string().describe('The refresh token string used to obtain a new access token.')
})

export const AuthControllerRefreshTokenResponse = zod.object({
  "accessToken": zod.string(),
  "refreshToken": zod.string()
})

/**
 * @summary Initiate password reset
 */
export const AuthControllerForgotPasswordBody = zod.object({
  "email": zod.string().describe('The email address of the user requesting a password reset')
})

/**
 * @summary Confirm password reset
 */
export const AuthControllerResetPasswordBody = zod.object({
  "token": zod.string().describe('JWT token for password reset'),
  "newPassword": zod.string().describe('New password for the user')
})

/**
 * @summary Update password (authenticated users)
 */
export const AuthControllerUpdatePasswordBody = zod.object({
  "newPassword": zod.string().describe('The new password for the user')
})

/**
 * @summary Update email address
 */
export const AuthControllerUpdateEmailBody = zod.object({
  "newEmail": zod.string().describe('The new email address of the user')
})

/**
 * @summary Verify email address
 */
export const AuthControllerVerifyEmailBody = zod.object({
  "email": zod.string().describe('The email address to be verified.'),
  "otp": zod.string().describe('The one-time password (OTP) sent to the email for verification.')
})

export const AuthControllerVerifyEmailResponse = zod.object({
  "accessToken": zod.string(),
  "refreshToken": zod.string(),
  "user": zod.object({
  "id": zod.string().describe('Unique identifier for the user'),
  "email": zod.string().describe('User email address'),
  "profilePicture": zod.string().describe('User profile picture url'),
  "role": zod.string().describe('User role'),
  "isEmailVerified": zod.boolean().describe('Email verification status'),
  "createdAt": zod.iso.datetime({}).describe('Account creation date')
})
})

/**
 * @summary Initiate email verification
 */
export const AuthControllerInitiateEmailVerificationBody = zod.object({
  "email": zod.email().optional()
})

