/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type { LlmModelDto } from "../../models";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type llmControllerListModelsResponse200 = {
	data: LlmModelDto[];
	status: 200;
};

export type llmControllerListModelsResponseSuccess =
	llmControllerListModelsResponse200 & {
		headers: Headers;
	};

export type llmControllerListModelsResponse =
	llmControllerListModelsResponseSuccess;

export const getLlmControllerListModelsUrl = () => {
	return `/llm/models`;
};

export const llmControllerListModels = async (
	options?: RequestInit,
): Promise<llmControllerListModelsResponse> => {
	return HttpClient<llmControllerListModelsResponse>(
		getLlmControllerListModelsUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getLlmControllerListModelsQueryKey = () => {
	return [`/llm/models`] as const;
};

export const getLlmControllerListModelsQueryOptions = <
	TData = Awaited<ReturnType<typeof llmControllerListModels>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof llmControllerListModels>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getLlmControllerListModelsQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof llmControllerListModels>>
	> = ({ signal }) => llmControllerListModels({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof llmControllerListModels>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LlmControllerListModelsQueryResult = NonNullable<
	Awaited<ReturnType<typeof llmControllerListModels>>
>;
export type LlmControllerListModelsQueryError = unknown;

export function useLlmControllerListModels<
	TData = Awaited<ReturnType<typeof llmControllerListModels>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof llmControllerListModels>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof llmControllerListModels>>,
					TError,
					Awaited<ReturnType<typeof llmControllerListModels>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLlmControllerListModels<
	TData = Awaited<ReturnType<typeof llmControllerListModels>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof llmControllerListModels>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof llmControllerListModels>>,
					TError,
					Awaited<ReturnType<typeof llmControllerListModels>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLlmControllerListModels<
	TData = Awaited<ReturnType<typeof llmControllerListModels>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof llmControllerListModels>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useLlmControllerListModels<
	TData = Awaited<ReturnType<typeof llmControllerListModels>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof llmControllerListModels>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getLlmControllerListModelsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
