/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Create a new extraction run
 */
export const runsControllerCreateBodyProcessingModeDefault = `unified`;export const runsControllerCreateBodyExtractionProviderDefault = `doclo`;

export const RunsControllerCreateBody = zod.object({
  "extractorId": zod.string().describe('The ID of the extractor to use for this run'),
  "sources": zod.array(zod.object({
  "type": zod.enum(['file', 'url']),
  "name": zod.string().describe('Display name for the source'),
  "url": zod.string().optional().describe('URL if type is url'),
  "fileId": zod.string().optional().describe('File ID if type is file')
})).describe('List of documents to process'),
  "processingMode": zod.enum(['unified', 'per_document']).default(runsControllerCreateBodyProcessingModeDefault),
  "extractionProvider": zod.enum(['doclo', 'langextract', 'freellm']).default(runsControllerCreateBodyExtractionProviderDefault),
  "variantId": zod.string().optional().describe('ID of schema variant to use for extraction'),
  "skippedFields": zod.array(zod.string()).optional().describe('Field names to exclude from extraction'),
  "model": zod.string().optional().describe('LLM model to use for extraction (overrides extractor default)')
})

/**
 * @summary Get all runs with pagination and filtering
 */
export const runsControllerFindAllQueryPageDefault = 1;

export const runsControllerFindAllQueryLimitDefault = 10;
export const runsControllerFindAllQueryLimitMax = 100;



export const RunsControllerFindAllQueryParams = zod.object({
  "page": zod.number().min(1).default(runsControllerFindAllQueryPageDefault).describe('Page number for pagination'),
  "limit": zod.number().min(1).max(runsControllerFindAllQueryLimitMax).default(runsControllerFindAllQueryLimitDefault).describe('Number of items per page'),
  "status": zod.enum(['pending', 'queued', 'parsing', 'extracting', 'done', 'failed', 'cancelled', 'review']).optional().describe('Filter runs by their current status'),
  "extractorId": zod.string().optional().describe('Filter runs by the extractor ID used'),
  "search": zod.string().optional().describe('Search term for run ID or name')
})

export const RunsControllerFindAllResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string(),
  "extractorId": zod.string(),
  "userId": zod.string(),
  "sources": zod.array(zod.string()),
  "processingMode": zod.enum(['unified', 'per_document']),
  "extractionProvider": zod.enum(['doclo', 'langextract', 'freellm']),
  "status": zod.enum(['pending', 'queued', 'parsing', 'extracting', 'done', 'failed', 'cancelled', 'review']),
  "progress": zod.object({

}).optional(),
  "results": zod.object({

}).optional(),
  "metrics": zod.object({

}).optional(),
  "logs": zod.array(zod.string()),
  "error": zod.object({

}).optional(),
  "confidence": zod.object({

}).optional(),
  "autorunId": zod.object({

}).optional(),
  "isAutorun": zod.boolean(),
  "variantId": zod.object({

}).optional().describe('ID of schema variant used for this run'),
  "skippedFields": zod.object({

}).optional().describe('Field names excluded from extraction'),
  "model": zod.object({

}).optional().describe('LLM model used for extraction'),
  "sortConfig": zod.object({

}).optional().describe('Reference sort configuration from uploaded XLSX'),
  "workflowExecutionId": zod.object({

}).optional(),
  "startedAt": zod.object({

}).optional(),
  "finishedAt": zod.object({

}).optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})),
  "total": zod.number(),
  "page": zod.number(),
  "limit": zod.number(),
  "statusCounts": zod.object({
  "done": zod.number(),
  "failed": zod.number()
})
})

/**
 * @summary Get a single run by ID
 */
export const RunsControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const RunsControllerFindOneResponse = zod.object({
  "id": zod.string(),
  "extractorId": zod.string(),
  "userId": zod.string(),
  "sources": zod.array(zod.string()),
  "processingMode": zod.enum(['unified', 'per_document']),
  "extractionProvider": zod.enum(['doclo', 'langextract', 'freellm']),
  "status": zod.enum(['pending', 'queued', 'parsing', 'extracting', 'done', 'failed', 'cancelled', 'review']),
  "progress": zod.object({

}).optional(),
  "results": zod.object({

}).optional(),
  "metrics": zod.object({

}).optional(),
  "logs": zod.array(zod.string()),
  "error": zod.object({

}).optional(),
  "confidence": zod.object({

}).optional(),
  "autorunId": zod.object({

}).optional(),
  "isAutorun": zod.boolean(),
  "variantId": zod.object({

}).optional().describe('ID of schema variant used for this run'),
  "skippedFields": zod.object({

}).optional().describe('Field names excluded from extraction'),
  "model": zod.object({

}).optional().describe('LLM model used for extraction'),
  "sortConfig": zod.object({

}).optional().describe('Reference sort configuration from uploaded XLSX'),
  "workflowExecutionId": zod.object({

}).optional(),
  "startedAt": zod.object({

}).optional(),
  "finishedAt": zod.object({

}).optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})

/**
 * @summary Update a run
 */
export const RunsControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const runsControllerUpdateBodyProcessingModeDefault = `unified`;export const runsControllerUpdateBodyExtractionProviderDefault = `doclo`;

export const RunsControllerUpdateBody = zod.object({
  "extractorId": zod.string().optional().describe('The ID of the extractor to use for this run'),
  "sources": zod.array(zod.object({
  "type": zod.enum(['file', 'url']),
  "name": zod.string().describe('Display name for the source'),
  "url": zod.string().optional().describe('URL if type is url'),
  "fileId": zod.string().optional().describe('File ID if type is file')
})).optional().describe('List of documents to process'),
  "processingMode": zod.enum(['unified', 'per_document']).default(runsControllerUpdateBodyProcessingModeDefault),
  "extractionProvider": zod.enum(['doclo', 'langextract', 'freellm']).default(runsControllerUpdateBodyExtractionProviderDefault),
  "variantId": zod.string().optional().describe('ID of schema variant to use for extraction'),
  "skippedFields": zod.array(zod.string()).optional().describe('Field names to exclude from extraction'),
  "model": zod.string().optional().describe('LLM model to use for extraction (overrides extractor default)'),
  "sortConfig": zod.object({

}).optional().describe('Reference sort configuration')
})

export const RunsControllerUpdateResponse = zod.object({
  "id": zod.string(),
  "extractorId": zod.string(),
  "userId": zod.string(),
  "sources": zod.array(zod.string()),
  "processingMode": zod.enum(['unified', 'per_document']),
  "extractionProvider": zod.enum(['doclo', 'langextract', 'freellm']),
  "status": zod.enum(['pending', 'queued', 'parsing', 'extracting', 'done', 'failed', 'cancelled', 'review']),
  "progress": zod.object({

}).optional(),
  "results": zod.object({

}).optional(),
  "metrics": zod.object({

}).optional(),
  "logs": zod.array(zod.string()),
  "error": zod.object({

}).optional(),
  "confidence": zod.object({

}).optional(),
  "autorunId": zod.object({

}).optional(),
  "isAutorun": zod.boolean(),
  "variantId": zod.object({

}).optional().describe('ID of schema variant used for this run'),
  "skippedFields": zod.object({

}).optional().describe('Field names excluded from extraction'),
  "model": zod.object({

}).optional().describe('LLM model used for extraction'),
  "sortConfig": zod.object({

}).optional().describe('Reference sort configuration from uploaded XLSX'),
  "workflowExecutionId": zod.object({

}).optional(),
  "startedAt": zod.object({

}).optional(),
  "finishedAt": zod.object({

}).optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})

/**
 * @summary Delete a run
 */
export const RunsControllerRemoveParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Retry a failed or cancelled run
 */
export const RunsControllerRetryParams = zod.object({
  "id": zod.string()
})

export const RunsControllerRetryResponse = zod.object({
  "id": zod.string(),
  "extractorId": zod.string(),
  "userId": zod.string(),
  "sources": zod.array(zod.string()),
  "processingMode": zod.enum(['unified', 'per_document']),
  "extractionProvider": zod.enum(['doclo', 'langextract', 'freellm']),
  "status": zod.enum(['pending', 'queued', 'parsing', 'extracting', 'done', 'failed', 'cancelled', 'review']),
  "progress": zod.object({

}).optional(),
  "results": zod.object({

}).optional(),
  "metrics": zod.object({

}).optional(),
  "logs": zod.array(zod.string()),
  "error": zod.object({

}).optional(),
  "confidence": zod.object({

}).optional(),
  "autorunId": zod.object({

}).optional(),
  "isAutorun": zod.boolean(),
  "variantId": zod.object({

}).optional().describe('ID of schema variant used for this run'),
  "skippedFields": zod.object({

}).optional().describe('Field names excluded from extraction'),
  "model": zod.object({

}).optional().describe('LLM model used for extraction'),
  "sortConfig": zod.object({

}).optional().describe('Reference sort configuration from uploaded XLSX'),
  "workflowExecutionId": zod.object({

}).optional(),
  "startedAt": zod.object({

}).optional(),
  "finishedAt": zod.object({

}).optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})

/**
 * @summary Batch retry specific sources with options
 */
export const RunsControllerRetrySourcesBatchParams = zod.object({
  "id": zod.string()
})

export const runsControllerRetrySourcesBatchBodyModeDefault = `extraction`;

export const RunsControllerRetrySourcesBatchBody = zod.object({
  "sourceIds": zod.array(zod.string()).describe('IDs of sources to retry'),
  "mode": zod.enum(['extraction', 'parse_and_extraction']).describe('Whether to retry extraction only, or re-parse and extract'),
  "schemaVariantId": zod.string().optional().describe('Schema variant ID to use. Null = default schema.'),
  "selectedFields": zod.array(zod.string()).optional().describe('Field names to include. Null = all fields.')
})

export const RunsControllerRetrySourcesBatchResponse = zod.object({
  "id": zod.string(),
  "extractorId": zod.string(),
  "userId": zod.string(),
  "sources": zod.array(zod.string()),
  "processingMode": zod.enum(['unified', 'per_document']),
  "extractionProvider": zod.enum(['doclo', 'langextract', 'freellm']),
  "status": zod.enum(['pending', 'queued', 'parsing', 'extracting', 'done', 'failed', 'cancelled', 'review']),
  "progress": zod.object({

}).optional(),
  "results": zod.object({

}).optional(),
  "metrics": zod.object({

}).optional(),
  "logs": zod.array(zod.string()),
  "error": zod.object({

}).optional(),
  "confidence": zod.object({

}).optional(),
  "autorunId": zod.object({

}).optional(),
  "isAutorun": zod.boolean(),
  "variantId": zod.object({

}).optional().describe('ID of schema variant used for this run'),
  "skippedFields": zod.object({

}).optional().describe('Field names excluded from extraction'),
  "model": zod.object({

}).optional().describe('LLM model used for extraction'),
  "sortConfig": zod.object({

}).optional().describe('Reference sort configuration from uploaded XLSX'),
  "workflowExecutionId": zod.object({

}).optional(),
  "startedAt": zod.object({

}).optional(),
  "finishedAt": zod.object({

}).optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})

/**
 * @summary Retry a single failed source within a run
 */
export const RunsControllerRetrySourceParams = zod.object({
  "id": zod.string(),
  "sourceId": zod.string()
})

export const RunsControllerRetrySourceResponse = zod.object({
  "id": zod.string(),
  "extractorId": zod.string(),
  "userId": zod.string(),
  "sources": zod.array(zod.string()),
  "processingMode": zod.enum(['unified', 'per_document']),
  "extractionProvider": zod.enum(['doclo', 'langextract', 'freellm']),
  "status": zod.enum(['pending', 'queued', 'parsing', 'extracting', 'done', 'failed', 'cancelled', 'review']),
  "progress": zod.object({

}).optional(),
  "results": zod.object({

}).optional(),
  "metrics": zod.object({

}).optional(),
  "logs": zod.array(zod.string()),
  "error": zod.object({

}).optional(),
  "confidence": zod.object({

}).optional(),
  "autorunId": zod.object({

}).optional(),
  "isAutorun": zod.boolean(),
  "variantId": zod.object({

}).optional().describe('ID of schema variant used for this run'),
  "skippedFields": zod.object({

}).optional().describe('Field names excluded from extraction'),
  "model": zod.object({

}).optional().describe('LLM model used for extraction'),
  "sortConfig": zod.object({

}).optional().describe('Reference sort configuration from uploaded XLSX'),
  "workflowExecutionId": zod.object({

}).optional(),
  "startedAt": zod.object({

}).optional(),
  "finishedAt": zod.object({

}).optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})

