/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Create a new extraction run
 */
export const runsControllerCreateBodyProcessingModeDefault = `unified`;export const runsControllerCreateBodyExtractionProviderDefault = `doclo`;

export const RunsControllerCreateBody = zod.object({
  "extractorId": zod.string().describe('Extractor to use for this run'),
  "sources": zod.array(zod.object({
  "type": zod.enum(['file', 'url']),
  "name": zod.string().describe('Display name for the source'),
  "url": zod.string().optional().describe('URL if type is url'),
  "fileId": zod.string().optional().describe('File ID if type is file')
})).describe('Documents to process'),
  "processingMode": zod.enum(['unified', 'per_document']).default(runsControllerCreateBodyProcessingModeDefault),
  "extractionProvider": zod.enum(['doclo', 'langextract']).default(runsControllerCreateBodyExtractionProviderDefault)
})

/**
 * @summary Get all runs with pagination and filtering
 */
export const runsControllerFindAllQueryPageDefault = 1;

export const runsControllerFindAllQueryLimitDefault = 10;
export const runsControllerFindAllQueryLimitMax = 100;



export const RunsControllerFindAllQueryParams = zod.object({
  "page": zod.number().min(1).default(runsControllerFindAllQueryPageDefault).describe('Page number'),
  "limit": zod.number().min(1).max(runsControllerFindAllQueryLimitMax).default(runsControllerFindAllQueryLimitDefault).describe('Items per page'),
  "status": zod.enum(['pending', 'queued', 'parsing', 'extracting', 'done', 'failed', 'cancelled', 'review']).optional().describe('Filter by run status'),
  "extractorId": zod.string().optional().describe('Filter by extractor ID'),
  "search": zod.string().optional().describe('Search by run ID or name')
})

/**
 * @summary Get a single run by ID
 */
export const RunsControllerFindOneParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Update a run
 */
export const RunsControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const runsControllerUpdateBodyProcessingModeDefault = `unified`;export const runsControllerUpdateBodyExtractionProviderDefault = `doclo`;

export const RunsControllerUpdateBody = zod.object({
  "extractorId": zod.string().optional().describe('Extractor to use for this run'),
  "sources": zod.array(zod.object({
  "type": zod.enum(['file', 'url']),
  "name": zod.string().describe('Display name for the source'),
  "url": zod.string().optional().describe('URL if type is url'),
  "fileId": zod.string().optional().describe('File ID if type is file')
})).optional().describe('Documents to process'),
  "processingMode": zod.enum(['unified', 'per_document']).default(runsControllerUpdateBodyProcessingModeDefault),
  "extractionProvider": zod.enum(['doclo', 'langextract']).default(runsControllerUpdateBodyExtractionProviderDefault)
})

/**
 * @summary Delete a run
 */
export const RunsControllerRemoveParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Retry a failed or cancelled run
 */
export const RunsControllerRetryParams = zod.object({
  "id": zod.string()
})

