/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const WebhookTriggerControllerHandleWebhookParams = zod.object({
  "workflowId": zod.string(),
  "path": zod.string()
})

