/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const inviteControllerCreateBodyRoleDefault = `user`;export const inviteControllerCreateBodyExpiresInHoursDefault = 48;

export const InviteControllerCreateBody = zod.object({
  "email": zod.string().optional().describe('Email to restrict the invite to (optional)'),
  "role": zod.enum(['user', 'admin']).default(inviteControllerCreateBodyRoleDefault).describe('Role for the invited user'),
  "expiresInHours": zod.number().default(inviteControllerCreateBodyExpiresInHoursDefault).describe('Invite expiry in hours (default: 48)')
})

export const InviteControllerFindAllQueryParams = zod.object({
  "page": zod.string(),
  "limit": zod.string()
})

export const InviteControllerValidateParams = zod.object({
  "token": zod.string()
})

export const InviteControllerAcceptParams = zod.object({
  "token": zod.string()
})

export const InviteControllerAcceptBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export const InviteControllerRevokeParams = zod.object({
  "id": zod.string()
})

