/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Get dashboard statistics
 */
export const DashboardControllerGetStatsResponse = zod.object({
  "totalDocuments": zod.number(),
  "activeExtractors": zod.number(),
  "pagesProcessed": zod.number(),
  "successRate": zod.number(),
  "recentRuns": zod.array(zod.object({
  "id": zod.string().describe('Run ID'),
  "extractorId": zod.string().describe('Extractor ID'),
  "extractorName": zod.string().describe('Extractor name'),
  "status": zod.string().describe('Run status'),
  "documentCount": zod.number().describe('Number of documents/sources'),
  "startedAt": zod.iso.datetime({}).describe('Started at timestamp'),
  "completedAt": zod.object({

}).nullish().describe('Completed at timestamp')
})),
  "extractionHistory": zod.array(zod.object({
  "id": zod.string().describe('Run ID'),
  "extractorId": zod.string().describe('Extractor ID'),
  "extractorName": zod.string().describe('Extractor name'),
  "status": zod.string().describe('Run status'),
  "documentCount": zod.number().describe('Number of documents/sources'),
  "startedAt": zod.iso.datetime({}).describe('Started at timestamp'),
  "completedAt": zod.object({

}).nullish().describe('Completed at timestamp')
})),
  "systemStats": zod.object({

})
})

