/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const ExtractorsControllerCreateBody = zod.object({

})

export const ExtractorsControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const ExtractorsControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const ExtractorsControllerUpdateBody = zod.object({

})

export const ExtractorsControllerRemoveParams = zod.object({
  "id": zod.string()
})

