ARG NODE_VERSION=22.15.0
ARG PNPM_VERSION=10.11.0

# ------------------ BUILD ------------------
FROM node:${NODE_VERSION}-alpine AS builder

ARG PNPM_VERSION

RUN npm install -g pnpm@${PNPM_VERSION}

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --store-dir /pnpm/store

COPY . .
RUN pnpm run build

# ------------------ PRODUCTION ------------------
FROM node:${NODE_VERSION}-alpine AS production

ARG PNPM_VERSION

RUN apk add --no-cache postgresql-client rclone
RUN npm install -g pnpm@${PNPM_VERSION}

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --prod --store-dir /pnpm/store

COPY --from=builder /app/dist ./dist

CMD ["node", "dist/main.js"]
