# ------------------ BUILD ------------------
FROM node:22-alpine AS builder

RUN npm install -g pnpm@9

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --store-dir /pnpm/store

COPY . .
RUN pnpm run build

# ------------------ PRODUCTION ------------------
FROM node:22-alpine AS production

RUN apk add --no-cache postgresql-client rclone
RUN npm install -g pnpm@9

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --prod --store-dir /pnpm/store

COPY --from=builder /app/dist ./dist

CMD ["node", "dist/main.js"]
