/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type { DashboardStatsDto } from "../../models";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get dashboard statistics
 */
export type dashboardControllerGetStatsResponse200 = {
	data: DashboardStatsDto;
	status: 200;
};

export type dashboardControllerGetStatsResponseSuccess =
	dashboardControllerGetStatsResponse200 & {
		headers: Headers;
	};

export type dashboardControllerGetStatsResponse =
	dashboardControllerGetStatsResponseSuccess;

export const getDashboardControllerGetStatsUrl = () => {
	return `/dashboard/stats`;
};

export const dashboardControllerGetStats = async (
	options?: RequestInit,
): Promise<dashboardControllerGetStatsResponse> => {
	return HttpClient<dashboardControllerGetStatsResponse>(
		getDashboardControllerGetStatsUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getDashboardControllerGetStatsQueryKey = () => {
	return [`/dashboard/stats`] as const;
};

export const getDashboardControllerGetStatsQueryOptions = <
	TData = Awaited<ReturnType<typeof dashboardControllerGetStats>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof dashboardControllerGetStats>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getDashboardControllerGetStatsQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof dashboardControllerGetStats>>
	> = ({ signal }) =>
		dashboardControllerGetStats({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof dashboardControllerGetStats>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DashboardControllerGetStatsQueryResult = NonNullable<
	Awaited<ReturnType<typeof dashboardControllerGetStats>>
>;
export type DashboardControllerGetStatsQueryError = unknown;

export function useDashboardControllerGetStats<
	TData = Awaited<ReturnType<typeof dashboardControllerGetStats>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof dashboardControllerGetStats>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof dashboardControllerGetStats>>,
					TError,
					Awaited<ReturnType<typeof dashboardControllerGetStats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashboardControllerGetStats<
	TData = Awaited<ReturnType<typeof dashboardControllerGetStats>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof dashboardControllerGetStats>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof dashboardControllerGetStats>>,
					TError,
					Awaited<ReturnType<typeof dashboardControllerGetStats>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashboardControllerGetStats<
	TData = Awaited<ReturnType<typeof dashboardControllerGetStats>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof dashboardControllerGetStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get dashboard statistics
 */

export function useDashboardControllerGetStats<
	TData = Awaited<ReturnType<typeof dashboardControllerGetStats>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof dashboardControllerGetStats>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getDashboardControllerGetStatsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
