/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	CreateExtractorDto,
	Extractor,
	GenerateExtractorDto,
	GenerateSchemaDto,
	UpdateExtractorDto,
} from "../../models";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new extractor
 */
export type extractorsControllerCreateResponse201 = {
	data: Extractor;
	status: 201;
};

export type extractorsControllerCreateResponseSuccess =
	extractorsControllerCreateResponse201 & {
		headers: Headers;
	};

export type extractorsControllerCreateResponse =
	extractorsControllerCreateResponseSuccess;

export const getExtractorsControllerCreateUrl = () => {
	return `/extractors`;
};

export const extractorsControllerCreate = async (
	createExtractorDto: CreateExtractorDto,
	options?: RequestInit,
): Promise<extractorsControllerCreateResponse> => {
	return HttpClient<extractorsControllerCreateResponse>(
		getExtractorsControllerCreateUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(createExtractorDto),
		},
	);
};

export const getExtractorsControllerCreateMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof extractorsControllerCreate>>,
		TError,
		{ data: CreateExtractorDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof extractorsControllerCreate>>,
	TError,
	{ data: CreateExtractorDto },
	TContext
> => {
	const mutationKey = ["extractorsControllerCreate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof extractorsControllerCreate>>,
		{ data: CreateExtractorDto }
	> = (props) => {
		const { data } = props ?? {};

		return extractorsControllerCreate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ExtractorsControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof extractorsControllerCreate>>
>;
export type ExtractorsControllerCreateMutationBody = CreateExtractorDto;
export type ExtractorsControllerCreateMutationError = unknown;

/**
 * @summary Create a new extractor
 */
export const useExtractorsControllerCreate = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof extractorsControllerCreate>>,
			TError,
			{ data: CreateExtractorDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof extractorsControllerCreate>>,
	TError,
	{ data: CreateExtractorDto },
	TContext
> => {
	return useMutation(
		getExtractorsControllerCreateMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Get all extractors
 */
export type extractorsControllerFindAllResponse200 = {
	data: Extractor[];
	status: 200;
};

export type extractorsControllerFindAllResponseSuccess =
	extractorsControllerFindAllResponse200 & {
		headers: Headers;
	};

export type extractorsControllerFindAllResponse =
	extractorsControllerFindAllResponseSuccess;

export const getExtractorsControllerFindAllUrl = () => {
	return `/extractors`;
};

export const extractorsControllerFindAll = async (
	options?: RequestInit,
): Promise<extractorsControllerFindAllResponse> => {
	return HttpClient<extractorsControllerFindAllResponse>(
		getExtractorsControllerFindAllUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getExtractorsControllerFindAllQueryKey = () => {
	return [`/extractors`] as const;
};

export const getExtractorsControllerFindAllQueryOptions = <
	TData = Awaited<ReturnType<typeof extractorsControllerFindAll>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof extractorsControllerFindAll>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getExtractorsControllerFindAllQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof extractorsControllerFindAll>>
	> = ({ signal }) =>
		extractorsControllerFindAll({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof extractorsControllerFindAll>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExtractorsControllerFindAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof extractorsControllerFindAll>>
>;
export type ExtractorsControllerFindAllQueryError = unknown;

export function useExtractorsControllerFindAll<
	TData = Awaited<ReturnType<typeof extractorsControllerFindAll>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof extractorsControllerFindAll>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof extractorsControllerFindAll>>,
					TError,
					Awaited<ReturnType<typeof extractorsControllerFindAll>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExtractorsControllerFindAll<
	TData = Awaited<ReturnType<typeof extractorsControllerFindAll>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof extractorsControllerFindAll>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof extractorsControllerFindAll>>,
					TError,
					Awaited<ReturnType<typeof extractorsControllerFindAll>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExtractorsControllerFindAll<
	TData = Awaited<ReturnType<typeof extractorsControllerFindAll>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof extractorsControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all extractors
 */

export function useExtractorsControllerFindAll<
	TData = Awaited<ReturnType<typeof extractorsControllerFindAll>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof extractorsControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getExtractorsControllerFindAllQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Generate a JSON schema from a description using AI
 */
export type extractorsControllerGenerateSchemaResponse201 = {
	data: void;
	status: 201;
};

export type extractorsControllerGenerateSchemaResponseSuccess =
	extractorsControllerGenerateSchemaResponse201 & {
		headers: Headers;
	};

export type extractorsControllerGenerateSchemaResponse =
	extractorsControllerGenerateSchemaResponseSuccess;

export const getExtractorsControllerGenerateSchemaUrl = () => {
	return `/extractors/generate-schema`;
};

export const extractorsControllerGenerateSchema = async (
	generateSchemaDto: GenerateSchemaDto,
	options?: RequestInit,
): Promise<extractorsControllerGenerateSchemaResponse> => {
	return HttpClient<extractorsControllerGenerateSchemaResponse>(
		getExtractorsControllerGenerateSchemaUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(generateSchemaDto),
		},
	);
};

export const getExtractorsControllerGenerateSchemaMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof extractorsControllerGenerateSchema>>,
		TError,
		{ data: GenerateSchemaDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof extractorsControllerGenerateSchema>>,
	TError,
	{ data: GenerateSchemaDto },
	TContext
> => {
	const mutationKey = ["extractorsControllerGenerateSchema"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof extractorsControllerGenerateSchema>>,
		{ data: GenerateSchemaDto }
	> = (props) => {
		const { data } = props ?? {};

		return extractorsControllerGenerateSchema(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ExtractorsControllerGenerateSchemaMutationResult = NonNullable<
	Awaited<ReturnType<typeof extractorsControllerGenerateSchema>>
>;
export type ExtractorsControllerGenerateSchemaMutationBody = GenerateSchemaDto;
export type ExtractorsControllerGenerateSchemaMutationError = unknown;

/**
 * @summary Generate a JSON schema from a description using AI
 */
export const useExtractorsControllerGenerateSchema = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof extractorsControllerGenerateSchema>>,
			TError,
			{ data: GenerateSchemaDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof extractorsControllerGenerateSchema>>,
	TError,
	{ data: GenerateSchemaDto },
	TContext
> => {
	return useMutation(
		getExtractorsControllerGenerateSchemaMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Generate a full extractor configuration from a description using AI
 */
export type extractorsControllerGenerateExtractorResponse201 = {
	data: void;
	status: 201;
};

export type extractorsControllerGenerateExtractorResponseSuccess =
	extractorsControllerGenerateExtractorResponse201 & {
		headers: Headers;
	};

export type extractorsControllerGenerateExtractorResponse =
	extractorsControllerGenerateExtractorResponseSuccess;

export const getExtractorsControllerGenerateExtractorUrl = () => {
	return `/extractors/generate-extractor`;
};

export const extractorsControllerGenerateExtractor = async (
	generateExtractorDto: GenerateExtractorDto,
	options?: RequestInit,
): Promise<extractorsControllerGenerateExtractorResponse> => {
	return HttpClient<extractorsControllerGenerateExtractorResponse>(
		getExtractorsControllerGenerateExtractorUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(generateExtractorDto),
		},
	);
};

export const getExtractorsControllerGenerateExtractorMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof extractorsControllerGenerateExtractor>>,
		TError,
		{ data: GenerateExtractorDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof extractorsControllerGenerateExtractor>>,
	TError,
	{ data: GenerateExtractorDto },
	TContext
> => {
	const mutationKey = ["extractorsControllerGenerateExtractor"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof extractorsControllerGenerateExtractor>>,
		{ data: GenerateExtractorDto }
	> = (props) => {
		const { data } = props ?? {};

		return extractorsControllerGenerateExtractor(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ExtractorsControllerGenerateExtractorMutationResult = NonNullable<
	Awaited<ReturnType<typeof extractorsControllerGenerateExtractor>>
>;
export type ExtractorsControllerGenerateExtractorMutationBody =
	GenerateExtractorDto;
export type ExtractorsControllerGenerateExtractorMutationError = unknown;

/**
 * @summary Generate a full extractor configuration from a description using AI
 */
export const useExtractorsControllerGenerateExtractor = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof extractorsControllerGenerateExtractor>>,
			TError,
			{ data: GenerateExtractorDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof extractorsControllerGenerateExtractor>>,
	TError,
	{ data: GenerateExtractorDto },
	TContext
> => {
	return useMutation(
		getExtractorsControllerGenerateExtractorMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Get an extractor by id
 */
export type extractorsControllerFindOneResponse200 = {
	data: Extractor;
	status: 200;
};

export type extractorsControllerFindOneResponseSuccess =
	extractorsControllerFindOneResponse200 & {
		headers: Headers;
	};

export type extractorsControllerFindOneResponse =
	extractorsControllerFindOneResponseSuccess;

export const getExtractorsControllerFindOneUrl = (id: string) => {
	return `/extractors/${id}`;
};

export const extractorsControllerFindOne = async (
	id: string,
	options?: RequestInit,
): Promise<extractorsControllerFindOneResponse> => {
	return HttpClient<extractorsControllerFindOneResponse>(
		getExtractorsControllerFindOneUrl(id),
		{
			...options,
			method: "GET",
		},
	);
};

export const getExtractorsControllerFindOneQueryKey = (id: string) => {
	return [`/extractors/${id}`] as const;
};

export const getExtractorsControllerFindOneQueryOptions = <
	TData = Awaited<ReturnType<typeof extractorsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof extractorsControllerFindOne>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getExtractorsControllerFindOneQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof extractorsControllerFindOne>>
	> = ({ signal }) =>
		extractorsControllerFindOne(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof extractorsControllerFindOne>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExtractorsControllerFindOneQueryResult = NonNullable<
	Awaited<ReturnType<typeof extractorsControllerFindOne>>
>;
export type ExtractorsControllerFindOneQueryError = unknown;

export function useExtractorsControllerFindOne<
	TData = Awaited<ReturnType<typeof extractorsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof extractorsControllerFindOne>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof extractorsControllerFindOne>>,
					TError,
					Awaited<ReturnType<typeof extractorsControllerFindOne>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExtractorsControllerFindOne<
	TData = Awaited<ReturnType<typeof extractorsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof extractorsControllerFindOne>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof extractorsControllerFindOne>>,
					TError,
					Awaited<ReturnType<typeof extractorsControllerFindOne>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExtractorsControllerFindOne<
	TData = Awaited<ReturnType<typeof extractorsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof extractorsControllerFindOne>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get an extractor by id
 */

export function useExtractorsControllerFindOne<
	TData = Awaited<ReturnType<typeof extractorsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof extractorsControllerFindOne>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getExtractorsControllerFindOneQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update an extractor by id
 */
export type extractorsControllerUpdateResponse200 = {
	data: Extractor;
	status: 200;
};

export type extractorsControllerUpdateResponseSuccess =
	extractorsControllerUpdateResponse200 & {
		headers: Headers;
	};

export type extractorsControllerUpdateResponse =
	extractorsControllerUpdateResponseSuccess;

export const getExtractorsControllerUpdateUrl = (id: string) => {
	return `/extractors/${id}`;
};

export const extractorsControllerUpdate = async (
	id: string,
	updateExtractorDto: UpdateExtractorDto,
	options?: RequestInit,
): Promise<extractorsControllerUpdateResponse> => {
	return HttpClient<extractorsControllerUpdateResponse>(
		getExtractorsControllerUpdateUrl(id),
		{
			...options,
			method: "PATCH",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(updateExtractorDto),
		},
	);
};

export const getExtractorsControllerUpdateMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof extractorsControllerUpdate>>,
		TError,
		{ id: string; data: UpdateExtractorDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof extractorsControllerUpdate>>,
	TError,
	{ id: string; data: UpdateExtractorDto },
	TContext
> => {
	const mutationKey = ["extractorsControllerUpdate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof extractorsControllerUpdate>>,
		{ id: string; data: UpdateExtractorDto }
	> = (props) => {
		const { id, data } = props ?? {};

		return extractorsControllerUpdate(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ExtractorsControllerUpdateMutationResult = NonNullable<
	Awaited<ReturnType<typeof extractorsControllerUpdate>>
>;
export type ExtractorsControllerUpdateMutationBody = UpdateExtractorDto;
export type ExtractorsControllerUpdateMutationError = unknown;

/**
 * @summary Update an extractor by id
 */
export const useExtractorsControllerUpdate = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof extractorsControllerUpdate>>,
			TError,
			{ id: string; data: UpdateExtractorDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof extractorsControllerUpdate>>,
	TError,
	{ id: string; data: UpdateExtractorDto },
	TContext
> => {
	return useMutation(
		getExtractorsControllerUpdateMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Delete an extractor by id
 */
export type extractorsControllerRemoveResponse200 = {
	data: void;
	status: 200;
};

export type extractorsControllerRemoveResponseSuccess =
	extractorsControllerRemoveResponse200 & {
		headers: Headers;
	};

export type extractorsControllerRemoveResponse =
	extractorsControllerRemoveResponseSuccess;

export const getExtractorsControllerRemoveUrl = (id: string) => {
	return `/extractors/${id}`;
};

export const extractorsControllerRemove = async (
	id: string,
	options?: RequestInit,
): Promise<extractorsControllerRemoveResponse> => {
	return HttpClient<extractorsControllerRemoveResponse>(
		getExtractorsControllerRemoveUrl(id),
		{
			...options,
			method: "DELETE",
		},
	);
};

export const getExtractorsControllerRemoveMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof extractorsControllerRemove>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof extractorsControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["extractorsControllerRemove"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof extractorsControllerRemove>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return extractorsControllerRemove(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ExtractorsControllerRemoveMutationResult = NonNullable<
	Awaited<ReturnType<typeof extractorsControllerRemove>>
>;

export type ExtractorsControllerRemoveMutationError = unknown;

/**
 * @summary Delete an extractor by id
 */
export const useExtractorsControllerRemove = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof extractorsControllerRemove>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof extractorsControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getExtractorsControllerRemoveMutationOptions(options),
		queryClient,
	);
};
