/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type { CreateWorkflowDto, UpdateWorkflowDto } from "../../models";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new workflow
 */
export type workflowsControllerCreateResponse201 = {
	data: void;
	status: 201;
};

export type workflowsControllerCreateResponseSuccess =
	workflowsControllerCreateResponse201 & {
		headers: Headers;
	};

export type workflowsControllerCreateResponse =
	workflowsControllerCreateResponseSuccess;

export const getWorkflowsControllerCreateUrl = () => {
	return `/workflows`;
};

export const workflowsControllerCreate = async (
	createWorkflowDto: CreateWorkflowDto,
	options?: RequestInit,
): Promise<workflowsControllerCreateResponse> => {
	return HttpClient<workflowsControllerCreateResponse>(
		getWorkflowsControllerCreateUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(createWorkflowDto),
		},
	);
};

export const getWorkflowsControllerCreateMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof workflowsControllerCreate>>,
		TError,
		{ data: CreateWorkflowDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof workflowsControllerCreate>>,
	TError,
	{ data: CreateWorkflowDto },
	TContext
> => {
	const mutationKey = ["workflowsControllerCreate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof workflowsControllerCreate>>,
		{ data: CreateWorkflowDto }
	> = (props) => {
		const { data } = props ?? {};

		return workflowsControllerCreate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type WorkflowsControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerCreate>>
>;
export type WorkflowsControllerCreateMutationBody = CreateWorkflowDto;
export type WorkflowsControllerCreateMutationError = unknown;

/**
 * @summary Create a new workflow
 */
export const useWorkflowsControllerCreate = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof workflowsControllerCreate>>,
			TError,
			{ data: CreateWorkflowDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof workflowsControllerCreate>>,
	TError,
	{ data: CreateWorkflowDto },
	TContext
> => {
	return useMutation(
		getWorkflowsControllerCreateMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Get all workflows for the current user
 */
export type workflowsControllerFindAllResponse200 = {
	data: void;
	status: 200;
};

export type workflowsControllerFindAllResponseSuccess =
	workflowsControllerFindAllResponse200 & {
		headers: Headers;
	};

export type workflowsControllerFindAllResponse =
	workflowsControllerFindAllResponseSuccess;

export const getWorkflowsControllerFindAllUrl = () => {
	return `/workflows`;
};

export const workflowsControllerFindAll = async (
	options?: RequestInit,
): Promise<workflowsControllerFindAllResponse> => {
	return HttpClient<workflowsControllerFindAllResponse>(
		getWorkflowsControllerFindAllUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getWorkflowsControllerFindAllQueryKey = () => {
	return [`/workflows`] as const;
};

export const getWorkflowsControllerFindAllQueryOptions = <
	TData = Awaited<ReturnType<typeof workflowsControllerFindAll>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof workflowsControllerFindAll>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getWorkflowsControllerFindAllQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof workflowsControllerFindAll>>
	> = ({ signal }) => workflowsControllerFindAll({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof workflowsControllerFindAll>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WorkflowsControllerFindAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerFindAll>>
>;
export type WorkflowsControllerFindAllQueryError = unknown;

export function useWorkflowsControllerFindAll<
	TData = Awaited<ReturnType<typeof workflowsControllerFindAll>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerFindAll>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof workflowsControllerFindAll>>,
					TError,
					Awaited<ReturnType<typeof workflowsControllerFindAll>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorkflowsControllerFindAll<
	TData = Awaited<ReturnType<typeof workflowsControllerFindAll>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerFindAll>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof workflowsControllerFindAll>>,
					TError,
					Awaited<ReturnType<typeof workflowsControllerFindAll>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorkflowsControllerFindAll<
	TData = Awaited<ReturnType<typeof workflowsControllerFindAll>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all workflows for the current user
 */

export function useWorkflowsControllerFindAll<
	TData = Awaited<ReturnType<typeof workflowsControllerFindAll>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getWorkflowsControllerFindAllQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a specific workflow
 */
export type workflowsControllerFindOneResponse200 = {
	data: void;
	status: 200;
};

export type workflowsControllerFindOneResponseSuccess =
	workflowsControllerFindOneResponse200 & {
		headers: Headers;
	};

export type workflowsControllerFindOneResponse =
	workflowsControllerFindOneResponseSuccess;

export const getWorkflowsControllerFindOneUrl = (id: string) => {
	return `/workflows/${id}`;
};

export const workflowsControllerFindOne = async (
	id: string,
	options?: RequestInit,
): Promise<workflowsControllerFindOneResponse> => {
	return HttpClient<workflowsControllerFindOneResponse>(
		getWorkflowsControllerFindOneUrl(id),
		{
			...options,
			method: "GET",
		},
	);
};

export const getWorkflowsControllerFindOneQueryKey = (id: string) => {
	return [`/workflows/${id}`] as const;
};

export const getWorkflowsControllerFindOneQueryOptions = <
	TData = Awaited<ReturnType<typeof workflowsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerFindOne>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getWorkflowsControllerFindOneQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof workflowsControllerFindOne>>
	> = ({ signal }) =>
		workflowsControllerFindOne(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof workflowsControllerFindOne>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WorkflowsControllerFindOneQueryResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerFindOne>>
>;
export type WorkflowsControllerFindOneQueryError = unknown;

export function useWorkflowsControllerFindOne<
	TData = Awaited<ReturnType<typeof workflowsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerFindOne>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof workflowsControllerFindOne>>,
					TError,
					Awaited<ReturnType<typeof workflowsControllerFindOne>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorkflowsControllerFindOne<
	TData = Awaited<ReturnType<typeof workflowsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerFindOne>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof workflowsControllerFindOne>>,
					TError,
					Awaited<ReturnType<typeof workflowsControllerFindOne>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorkflowsControllerFindOne<
	TData = Awaited<ReturnType<typeof workflowsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerFindOne>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a specific workflow
 */

export function useWorkflowsControllerFindOne<
	TData = Awaited<ReturnType<typeof workflowsControllerFindOne>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerFindOne>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getWorkflowsControllerFindOneQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a workflow
 */
export type workflowsControllerUpdateResponse200 = {
	data: void;
	status: 200;
};

export type workflowsControllerUpdateResponseSuccess =
	workflowsControllerUpdateResponse200 & {
		headers: Headers;
	};

export type workflowsControllerUpdateResponse =
	workflowsControllerUpdateResponseSuccess;

export const getWorkflowsControllerUpdateUrl = (id: string) => {
	return `/workflows/${id}`;
};

export const workflowsControllerUpdate = async (
	id: string,
	updateWorkflowDto: UpdateWorkflowDto,
	options?: RequestInit,
): Promise<workflowsControllerUpdateResponse> => {
	return HttpClient<workflowsControllerUpdateResponse>(
		getWorkflowsControllerUpdateUrl(id),
		{
			...options,
			method: "PATCH",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(updateWorkflowDto),
		},
	);
};

export const getWorkflowsControllerUpdateMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof workflowsControllerUpdate>>,
		TError,
		{ id: string; data: UpdateWorkflowDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof workflowsControllerUpdate>>,
	TError,
	{ id: string; data: UpdateWorkflowDto },
	TContext
> => {
	const mutationKey = ["workflowsControllerUpdate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof workflowsControllerUpdate>>,
		{ id: string; data: UpdateWorkflowDto }
	> = (props) => {
		const { id, data } = props ?? {};

		return workflowsControllerUpdate(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type WorkflowsControllerUpdateMutationResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerUpdate>>
>;
export type WorkflowsControllerUpdateMutationBody = UpdateWorkflowDto;
export type WorkflowsControllerUpdateMutationError = unknown;

/**
 * @summary Update a workflow
 */
export const useWorkflowsControllerUpdate = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof workflowsControllerUpdate>>,
			TError,
			{ id: string; data: UpdateWorkflowDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof workflowsControllerUpdate>>,
	TError,
	{ id: string; data: UpdateWorkflowDto },
	TContext
> => {
	return useMutation(
		getWorkflowsControllerUpdateMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Delete a workflow
 */
export type workflowsControllerRemoveResponse200 = {
	data: void;
	status: 200;
};

export type workflowsControllerRemoveResponseSuccess =
	workflowsControllerRemoveResponse200 & {
		headers: Headers;
	};

export type workflowsControllerRemoveResponse =
	workflowsControllerRemoveResponseSuccess;

export const getWorkflowsControllerRemoveUrl = (id: string) => {
	return `/workflows/${id}`;
};

export const workflowsControllerRemove = async (
	id: string,
	options?: RequestInit,
): Promise<workflowsControllerRemoveResponse> => {
	return HttpClient<workflowsControllerRemoveResponse>(
		getWorkflowsControllerRemoveUrl(id),
		{
			...options,
			method: "DELETE",
		},
	);
};

export const getWorkflowsControllerRemoveMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof workflowsControllerRemove>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof workflowsControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["workflowsControllerRemove"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof workflowsControllerRemove>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return workflowsControllerRemove(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type WorkflowsControllerRemoveMutationResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerRemove>>
>;

export type WorkflowsControllerRemoveMutationError = unknown;

/**
 * @summary Delete a workflow
 */
export const useWorkflowsControllerRemove = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof workflowsControllerRemove>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof workflowsControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getWorkflowsControllerRemoveMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Activate a workflow
 */
export type workflowsControllerActivateResponse201 = {
	data: void;
	status: 201;
};

export type workflowsControllerActivateResponseSuccess =
	workflowsControllerActivateResponse201 & {
		headers: Headers;
	};

export type workflowsControllerActivateResponse =
	workflowsControllerActivateResponseSuccess;

export const getWorkflowsControllerActivateUrl = (id: string) => {
	return `/workflows/${id}/activate`;
};

export const workflowsControllerActivate = async (
	id: string,
	options?: RequestInit,
): Promise<workflowsControllerActivateResponse> => {
	return HttpClient<workflowsControllerActivateResponse>(
		getWorkflowsControllerActivateUrl(id),
		{
			...options,
			method: "POST",
		},
	);
};

export const getWorkflowsControllerActivateMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof workflowsControllerActivate>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof workflowsControllerActivate>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["workflowsControllerActivate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof workflowsControllerActivate>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return workflowsControllerActivate(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type WorkflowsControllerActivateMutationResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerActivate>>
>;

export type WorkflowsControllerActivateMutationError = unknown;

/**
 * @summary Activate a workflow
 */
export const useWorkflowsControllerActivate = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof workflowsControllerActivate>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof workflowsControllerActivate>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getWorkflowsControllerActivateMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Pause a workflow
 */
export type workflowsControllerPauseResponse201 = {
	data: void;
	status: 201;
};

export type workflowsControllerPauseResponseSuccess =
	workflowsControllerPauseResponse201 & {
		headers: Headers;
	};

export type workflowsControllerPauseResponse =
	workflowsControllerPauseResponseSuccess;

export const getWorkflowsControllerPauseUrl = (id: string) => {
	return `/workflows/${id}/pause`;
};

export const workflowsControllerPause = async (
	id: string,
	options?: RequestInit,
): Promise<workflowsControllerPauseResponse> => {
	return HttpClient<workflowsControllerPauseResponse>(
		getWorkflowsControllerPauseUrl(id),
		{
			...options,
			method: "POST",
		},
	);
};

export const getWorkflowsControllerPauseMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof workflowsControllerPause>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof workflowsControllerPause>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["workflowsControllerPause"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof workflowsControllerPause>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return workflowsControllerPause(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type WorkflowsControllerPauseMutationResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerPause>>
>;

export type WorkflowsControllerPauseMutationError = unknown;

/**
 * @summary Pause a workflow
 */
export const useWorkflowsControllerPause = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof workflowsControllerPause>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof workflowsControllerPause>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getWorkflowsControllerPauseMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Get execution history for a workflow
 */
export type workflowsControllerGetExecutionsResponse200 = {
	data: void;
	status: 200;
};

export type workflowsControllerGetExecutionsResponseSuccess =
	workflowsControllerGetExecutionsResponse200 & {
		headers: Headers;
	};

export type workflowsControllerGetExecutionsResponse =
	workflowsControllerGetExecutionsResponseSuccess;

export const getWorkflowsControllerGetExecutionsUrl = (id: string) => {
	return `/workflows/${id}/executions`;
};

export const workflowsControllerGetExecutions = async (
	id: string,
	options?: RequestInit,
): Promise<workflowsControllerGetExecutionsResponse> => {
	return HttpClient<workflowsControllerGetExecutionsResponse>(
		getWorkflowsControllerGetExecutionsUrl(id),
		{
			...options,
			method: "GET",
		},
	);
};

export const getWorkflowsControllerGetExecutionsQueryKey = (id: string) => {
	return [`/workflows/${id}/executions`] as const;
};

export const getWorkflowsControllerGetExecutionsQueryOptions = <
	TData = Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getWorkflowsControllerGetExecutionsQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof workflowsControllerGetExecutions>>
	> = ({ signal }) =>
		workflowsControllerGetExecutions(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WorkflowsControllerGetExecutionsQueryResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerGetExecutions>>
>;
export type WorkflowsControllerGetExecutionsQueryError = unknown;

export function useWorkflowsControllerGetExecutions<
	TData = Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
	TError = unknown,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
					TError,
					Awaited<ReturnType<typeof workflowsControllerGetExecutions>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorkflowsControllerGetExecutions<
	TData = Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
					TError,
					Awaited<ReturnType<typeof workflowsControllerGetExecutions>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorkflowsControllerGetExecutions<
	TData = Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get execution history for a workflow
 */

export function useWorkflowsControllerGetExecutions<
	TData = Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
	TError = unknown,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerGetExecutions>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getWorkflowsControllerGetExecutionsQueryOptions(
		id,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Manually trigger a workflow
 */
export type workflowsControllerTriggerResponse201 = {
	data: void;
	status: 201;
};

export type workflowsControllerTriggerResponseSuccess =
	workflowsControllerTriggerResponse201 & {
		headers: Headers;
	};

export type workflowsControllerTriggerResponse =
	workflowsControllerTriggerResponseSuccess;

export const getWorkflowsControllerTriggerUrl = (id: string) => {
	return `/workflows/${id}/trigger`;
};

export const workflowsControllerTrigger = async (
	id: string,
	options?: RequestInit,
): Promise<workflowsControllerTriggerResponse> => {
	return HttpClient<workflowsControllerTriggerResponse>(
		getWorkflowsControllerTriggerUrl(id),
		{
			...options,
			method: "POST",
		},
	);
};

export const getWorkflowsControllerTriggerMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof workflowsControllerTrigger>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof workflowsControllerTrigger>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["workflowsControllerTrigger"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof workflowsControllerTrigger>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return workflowsControllerTrigger(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type WorkflowsControllerTriggerMutationResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerTrigger>>
>;

export type WorkflowsControllerTriggerMutationError = unknown;

/**
 * @summary Manually trigger a workflow
 */
export const useWorkflowsControllerTrigger = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof workflowsControllerTrigger>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof workflowsControllerTrigger>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getWorkflowsControllerTriggerMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Get all available node types with metadata
 */
export type workflowsControllerGetNodeMetadataResponse200 = {
	data: void;
	status: 200;
};

export type workflowsControllerGetNodeMetadataResponseSuccess =
	workflowsControllerGetNodeMetadataResponse200 & {
		headers: Headers;
	};

export type workflowsControllerGetNodeMetadataResponse =
	workflowsControllerGetNodeMetadataResponseSuccess;

export const getWorkflowsControllerGetNodeMetadataUrl = () => {
	return `/workflows/nodes/metadata`;
};

export const workflowsControllerGetNodeMetadata = async (
	options?: RequestInit,
): Promise<workflowsControllerGetNodeMetadataResponse> => {
	return HttpClient<workflowsControllerGetNodeMetadataResponse>(
		getWorkflowsControllerGetNodeMetadataUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getWorkflowsControllerGetNodeMetadataQueryKey = () => {
	return [`/workflows/nodes/metadata`] as const;
};

export const getWorkflowsControllerGetNodeMetadataQueryOptions = <
	TData = Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getWorkflowsControllerGetNodeMetadataQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>
	> = ({ signal }) =>
		workflowsControllerGetNodeMetadata({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WorkflowsControllerGetNodeMetadataQueryResult = NonNullable<
	Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>
>;
export type WorkflowsControllerGetNodeMetadataQueryError = unknown;

export function useWorkflowsControllerGetNodeMetadata<
	TData = Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
					TError,
					Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorkflowsControllerGetNodeMetadata<
	TData = Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
					TError,
					Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorkflowsControllerGetNodeMetadata<
	TData = Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all available node types with metadata
 */

export function useWorkflowsControllerGetNodeMetadata<
	TData = Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof workflowsControllerGetNodeMetadata>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions =
		getWorkflowsControllerGetNodeMetadataQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
