/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Send a message to the AI chat
 */
export const ChatControllerCreateBody = zod.object({
  "messages": zod.array(zod.object({
  "role": zod.string().describe('The role of the sender, e.g., \"user\" or \"assistant\"'),
  "content": zod.string().describe('The actual message content')
})).describe('Array of messages between user and assistant')
})

