/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type webhookTriggerControllerHandleWebhookResponse201 = {
	data: void;
	status: 201;
};

export type webhookTriggerControllerHandleWebhookResponseSuccess =
	webhookTriggerControllerHandleWebhookResponse201 & {
		headers: Headers;
	};

export type webhookTriggerControllerHandleWebhookResponse =
	webhookTriggerControllerHandleWebhookResponseSuccess;

export const getWebhookTriggerControllerHandleWebhookUrl = (
	workflowId: string,
	path: string,
) => {
	return `/webhooks/${workflowId}/${path}`;
};

export const webhookTriggerControllerHandleWebhook = async (
	workflowId: string,
	path: string,
	options?: RequestInit,
): Promise<webhookTriggerControllerHandleWebhookResponse> => {
	return HttpClient<webhookTriggerControllerHandleWebhookResponse>(
		getWebhookTriggerControllerHandleWebhookUrl(workflowId, path),
		{
			...options,
			method: "POST",
		},
	);
};

export const getWebhookTriggerControllerHandleWebhookMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof webhookTriggerControllerHandleWebhook>>,
		TError,
		{ workflowId: string; path: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof webhookTriggerControllerHandleWebhook>>,
	TError,
	{ workflowId: string; path: string },
	TContext
> => {
	const mutationKey = ["webhookTriggerControllerHandleWebhook"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof webhookTriggerControllerHandleWebhook>>,
		{ workflowId: string; path: string }
	> = (props) => {
		const { workflowId, path } = props ?? {};

		return webhookTriggerControllerHandleWebhook(
			workflowId,
			path,
			requestOptions,
		);
	};

	return { mutationFn, ...mutationOptions };
};

export type WebhookTriggerControllerHandleWebhookMutationResult = NonNullable<
	Awaited<ReturnType<typeof webhookTriggerControllerHandleWebhook>>
>;

export type WebhookTriggerControllerHandleWebhookMutationError = unknown;

export const useWebhookTriggerControllerHandleWebhook = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof webhookTriggerControllerHandleWebhook>>,
			TError,
			{ workflowId: string; path: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof webhookTriggerControllerHandleWebhook>>,
	TError,
	{ workflowId: string; path: string },
	TContext
> => {
	return useMutation(
		getWebhookTriggerControllerHandleWebhookMutationOptions(options),
		queryClient,
	);
};
