/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoRole } from "./createUserDtoRole";

export interface CreateUserDto {
	email: string;
	profilePicture?: string;
	password?: string;
	googleId?: string;
	role: CreateUserDtoRole;
}
