/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

/**
 * Parser engine used for document parsing
 */
export type CreateExtractorDtoParserEngine =
	(typeof CreateExtractorDtoParserEngine)[keyof typeof CreateExtractorDtoParserEngine];

export const CreateExtractorDtoParserEngine = {
	docling: "docling",
	markitdown: "markitdown",
	pymupdf: "pymupdf",
	opendataloader: "opendataloader",
} as const;
