/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { CreateInviteDtoRole } from "./createInviteDtoRole";

export interface CreateInviteDto {
	/** Email to restrict the invite to (optional) */
	email?: string;
	/** Role for the invited user */
	role?: CreateInviteDtoRole;
	/** Invite expiry in hours (default: 48) */
	expiresInHours?: number;
}
