/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { CreateSchemaVariantDtoSchema } from "./createSchemaVariantDtoSchema";

export interface CreateSchemaVariantDto {
	name: string;
	description?: string;
	schema: CreateSchemaVariantDtoSchema;
	isDefault?: boolean;
}
