/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type CreateRunDtoProcessingMode =
	(typeof CreateRunDtoProcessingMode)[keyof typeof CreateRunDtoProcessingMode];

export const CreateRunDtoProcessingMode = {
	unified: "unified",
	per_document: "per_document",
} as const;
