/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { MessageDto } from "./messageDto";

export interface CreateChatDto {
	/** Array of messages between user and assistant */
	messages: MessageDto[];
}
