/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { CreateRunDtoExtractionProvider } from "./createRunDtoExtractionProvider";
import type { CreateRunDtoProcessingMode } from "./createRunDtoProcessingMode";
import type { RunSourceDto } from "./runSourceDto";

export interface CreateRunDto {
	/** Extractor to use for this run */
	extractorId: string;
	/** Documents to process */
	sources: RunSourceDto[];
	processingMode?: CreateRunDtoProcessingMode;
	extractionProvider?: CreateRunDtoExtractionProvider;
}
