/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { CreateExtractorDtoConflictResolution } from "./createExtractorDtoConflictResolution";
import type { CreateExtractorDtoParserEngine } from "./createExtractorDtoParserEngine";
import type { CreateExtractorDtoSchema } from "./createExtractorDtoSchema";
import type { FewShotExampleDto } from "./fewShotExampleDto";

export interface CreateExtractorDto {
	/** The name of the extractor */
	name: string;
	/** The description of the extractor */
	description?: string;
	thumbnailUrl?: string;
	schema: CreateExtractorDtoSchema;
	systemPrompt: string;
	fewShotExamples?: FewShotExampleDto[];
	consensusEnabled?: boolean;
	/**
	 * @minimum 0
	 * @maximum 100
	 */
	confidenceThreshold?: number;
	conflictResolution?: CreateExtractorDtoConflictResolution;
	/** Parser engine used for document parsing */
	parserEngine?: CreateExtractorDtoParserEngine;
	citationEnabled?: boolean;
	citationIncludePdfPage?: boolean;
	citationIncludeBbox?: boolean;
	citationIncludeParagraphId?: boolean;
	contextWindow?: string;
	defaultModel?: string;
}
