/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type CreateRunDtoExtractionProvider =
	(typeof CreateRunDtoExtractionProvider)[keyof typeof CreateRunDtoExtractionProvider];

export const CreateRunDtoExtractionProvider = {
	doclo: "doclo",
	langextract: "langextract",
} as const;
