/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

/**
 * Role for the invited user
 */
export type CreateInviteDtoRole =
	(typeof CreateInviteDtoRole)[keyof typeof CreateInviteDtoRole];

export const CreateInviteDtoRole = {
	user: "user",
	admin: "admin",
} as const;
