/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { DashboardStatsDtoSystemStats } from "./dashboardStatsDtoSystemStats";
import type { RunSummaryDto } from "./runSummaryDto";

export interface DashboardStatsDto {
	totalDocuments: number;
	activeExtractors: number;
	pagesProcessed: number;
	successRate: number;
	recentRuns: RunSummaryDto[];
	extractionHistory: RunSummaryDto[];
	systemStats: DashboardStatsDtoSystemStats;
}
