/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

/**
 * Parser engine used for document parsing
 */
export type ExtractorParserEngine =
	(typeof ExtractorParserEngine)[keyof typeof ExtractorParserEngine];

export const ExtractorParserEngine = {
	docling: "docling",
	markitdown: "markitdown",
	pymupdf: "pymupdf",
	opendataloader: "opendataloader",
} as const;
