/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { ExtractorConflictResolution } from "./extractorConflictResolution";
import type { ExtractorFewShotExamplesItem } from "./extractorFewShotExamplesItem";
import type { ExtractorSchema } from "./extractorSchema";

export interface Extractor {
	id: string;
	name: string;
	description?: string;
	thumbnailUrl?: string;
	schema: ExtractorSchema;
	systemPrompt: string;
	fewShotExamples?: ExtractorFewShotExamplesItem[];
	consensusEnabled?: boolean;
	confidenceThreshold?: number;
	conflictResolution?: ExtractorConflictResolution;
	citationEnabled?: boolean;
	citationIncludePdfPage?: boolean;
	citationIncludeBbox?: boolean;
	citationIncludeParagraphId?: boolean;
	contextWindow?: string;
	defaultModel?: string;
	createdAt: string;
	updatedAt: string;
}
