/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type ExtractorConflictResolution =
	(typeof ExtractorConflictResolution)[keyof typeof ExtractorConflictResolution];

export const ExtractorConflictResolution = {
	majority: "majority",
	highest_confidence: "highest_confidence",
	human_review: "human_review",
	conservative: "conservative",
} as const;
