/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type FewShotExampleSourceDtoType =
	(typeof FewShotExampleSourceDtoType)[keyof typeof FewShotExampleSourceDtoType];

export const FewShotExampleSourceDtoType = {
	file: "file",
	url: "url",
	text: "text",
} as const;
