/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { FewShotExampleSourceDtoType } from "./fewShotExampleSourceDtoType";

export interface FewShotExampleSourceDto {
	id: string;
	type: FewShotExampleSourceDtoType;
	name: string;
	description: string;
	content: string;
}
