/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { FewShotExampleSourceDto } from "./fewShotExampleSourceDto";

export interface FewShotExampleDto {
	id: string;
	name: string;
	sources: FewShotExampleSourceDto[];
	output: string;
}
