/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type FilesControllerUploadFile201 = {
	/** Unique file ID */
	id?: string;
	/** Direct URL to access the file */
	url?: string;
	/** S3 storage key for the file */
	storageKey?: string;
};
