/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type FilesControllerUploadMultipleFilesBody = {
	/** Array of files to upload (max 10) */
	files: string[];
	/** User ID (will be extracted from JWT token in production) */
	userId: string;
	/** Optional JSON metadata applied to all files */
	metadata?: string;
};
