/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type FilesControllerUploadFileBody = {
	/** The file to upload */
	file: Blob;
	/** User ID (will be extracted from JWT token in production) */
	userId: string;
	/** Optional JSON metadata (e.g., {"jobId": "job-456"}) */
	metadata?: string;
};
