/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type FilesControllerListFiles200Item = {
	id?: string;
	originalName?: string;
	mimeType?: string;
	size?: number;
	status?: string;
	createdAt?: string;
};
