/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export interface GenerateExtractorDto {
	/** A description of the extractor to generate, including what documents it processes and what data to extract */
	description: string;
}
