/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export interface ImapConfigDto {
	host: string;
	port: number;
	user: string;
	password: string;
	folder: string;
	filterSubject?: string;
	filterFrom?: string;
}
