/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
	/** The email address of the user */
	email: string;
	/** The password of the user */
	password: string;
}
