/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export interface MessageDto {
	/** The role of the sender, e.g., "user" or "assistant" */
	role: string;
	/** The actual message content */
	content: string;
}
