/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { Run } from "./run";
import type { StatusCountsDto } from "./statusCountsDto";

export interface PaginatedRunsDto {
	data: Run[];
	total: number;
	page: number;
	limit: number;
	statusCounts: StatusCountsDto;
}
