/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { RetrySourcesDtoMode } from "./retrySourcesDtoMode";

export interface RetrySourcesDto {
	/** IDs of sources to retry */
	sourceIds: string[];
	/** Whether to retry extraction only, or re-parse and extract */
	mode: RetrySourcesDtoMode;
	/** Schema variant ID to use. Null = default schema. */
	schemaVariantId?: string;
	/** Field names to include. Null = all fields. */
	selectedFields?: string[];
}
