/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

/**
 * Whether to retry extraction only, or re-parse and extract
 */
export type RetrySourcesDtoMode =
	(typeof RetrySourcesDtoMode)[keyof typeof RetrySourcesDtoMode];

export const RetrySourcesDtoMode = {
	extraction: "extraction",
	parse_and_extraction: "parse_and_extraction",
} as const;
