/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { RunAutorunId } from "./runAutorunId";
import type { RunConfidence } from "./runConfidence";
import type { RunError } from "./runError";
import type { RunExtractionProvider } from "./runExtractionProvider";
import type { RunFinishedAt } from "./runFinishedAt";
import type { RunMetrics } from "./runMetrics";
import type { RunProcessingMode } from "./runProcessingMode";
import type { RunProgress } from "./runProgress";
import type { RunResults } from "./runResults";
import type { RunSkippedFields } from "./runSkippedFields";
import type { RunSortConfig } from "./runSortConfig";
import type { RunStartedAt } from "./runStartedAt";
import type { RunStatus } from "./runStatus";
import type { RunVariantId } from "./runVariantId";
import type { RunWorkflowExecutionId } from "./runWorkflowExecutionId";

export interface Run {
	id: string;
	extractorId: string;
	userId: string;
	sources: string[];
	processingMode: RunProcessingMode;
	extractionProvider: RunExtractionProvider;
	status: RunStatus;
	progress?: RunProgress;
	results?: RunResults;
	metrics?: RunMetrics;
	logs: string[];
	error?: RunError;
	confidence?: RunConfidence;
	autorunId?: RunAutorunId;
	isAutorun: boolean;
	isDemo?: boolean;
	/** ID of schema variant used for this run */
	variantId?: RunVariantId;
	/** Field names excluded from extraction */
	skippedFields?: RunSkippedFields;
	/** Reference sort configuration from uploaded XLSX */
	sortConfig?: RunSortConfig;
	workflowExecutionId?: RunWorkflowExecutionId;
	startedAt?: RunStartedAt;
	finishedAt?: RunFinishedAt;
	createdAt: string;
	updatedAt: string;
}
