/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type RunProcessingMode =
	(typeof RunProcessingMode)[keyof typeof RunProcessingMode];

export const RunProcessingMode = {
	unified: "unified",
	per_document: "per_document",
} as const;
