/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { RunsControllerFindAllStatus } from "./runsControllerFindAllStatus";

export type RunsControllerFindAllParams = {
	/**
	 * Page number for pagination
	 * @minimum 1
	 */
	page?: number;
	/**
	 * Number of items per page
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * Filter runs by their current status
	 */
	status?: RunsControllerFindAllStatus;
	/**
	 * Filter runs by the extractor ID used
	 */
	extractorId?: string;
	/**
	 * Search term for run ID or name
	 */
	search?: string;
};
