/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { RunsControllerFindAllStatus } from "./runsControllerFindAllStatus";

export type RunsControllerFindAllParams = {
	/**
	 * Page number
	 * @minimum 1
	 */
	page?: number;
	/**
	 * Items per page
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
	/**
	 * Filter by run status
	 */
	status?: RunsControllerFindAllStatus;
	/**
	 * Filter by extractor ID
	 */
	extractorId?: string;
	/**
	 * Search by run ID or name
	 */
	search?: string;
};
