/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type RunStatus = (typeof RunStatus)[keyof typeof RunStatus];

export const RunStatus = {
	pending: "pending",
	queued: "queued",
	parsing: "parsing",
	extracting: "extracting",
	done: "done",
	failed: "failed",
	cancelled: "cancelled",
	review: "review",
} as const;
