/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { RunSummaryDtoCompletedAt } from "./runSummaryDtoCompletedAt";

export interface RunSummaryDto {
	/** Run ID */
	id: string;
	/** Extractor ID */
	extractorId: string;
	/** Extractor name */
	extractorName: string;
	/** Run status */
	status: string;
	/** Number of documents/sources */
	documentCount: number;
	/** Started at timestamp */
	startedAt: string;
	/**
	 * Completed at timestamp
	 * @nullable
	 */
	completedAt?: RunSummaryDtoCompletedAt;
}
