/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

/**
 * Field names excluded from extraction
 */
export type RunSkippedFields = { [key: string]: unknown };
