/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type RunSourceDtoType =
	(typeof RunSourceDtoType)[keyof typeof RunSourceDtoType];

export const RunSourceDtoType = {
	file: "file",
	url: "url",
} as const;
