/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type TriggerConfigDtoType =
	(typeof TriggerConfigDtoType)[keyof typeof TriggerConfigDtoType];

export const TriggerConfigDtoType = {
	webhook: "webhook",
	email: "email",
	schedule: "schedule",
	google_drive: "google_drive",
	s3: "s3",
} as const;
