/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { ImapConfigDto } from "./imapConfigDto";
import type { TriggerConfigDtoType } from "./triggerConfigDtoType";

export interface TriggerConfigDto {
	type: TriggerConfigDtoType;
	webhookPath?: string;
	imapConfig?: ImapConfigDto;
	cronExpression?: string;
	timezone?: string;
}
