/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { TriggerConfigDto } from "./triggerConfigDto";
import type { WorkflowDefinitionDto } from "./workflowDefinitionDto";

export interface UpdateWorkflowDto {
	name?: string;
	description?: string;
	definition?: WorkflowDefinitionDto;
	triggerConfig?: TriggerConfigDto;
}
