/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type UpdateRunDtoProcessingMode =
	(typeof UpdateRunDtoProcessingMode)[keyof typeof UpdateRunDtoProcessingMode];

export const UpdateRunDtoProcessingMode = {
	unified: "unified",
	per_document: "per_document",
} as const;
