/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export type UpdateRunDtoExtractionProvider =
	(typeof UpdateRunDtoExtractionProvider)[keyof typeof UpdateRunDtoExtractionProvider];

export const UpdateRunDtoExtractionProvider = {
	doclo: "doclo",
	langextract: "langextract",
	freellm: "freellm",
} as const;
