/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { RunSourceDto } from "./runSourceDto";
import type { UpdateRunDtoExtractionProvider } from "./updateRunDtoExtractionProvider";
import type { UpdateRunDtoProcessingMode } from "./updateRunDtoProcessingMode";

export interface UpdateRunDto {
	/** Extractor to use for this run */
	extractorId?: string;
	/** Documents to process */
	sources?: RunSourceDto[];
	processingMode?: UpdateRunDtoProcessingMode;
	extractionProvider?: UpdateRunDtoExtractionProvider;
}
