/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export interface UpdateInstanceSettingsDto {
	instanceName?: string;
	allowPublicSignup?: boolean;
	smtpHost?: string;
	smtpPort?: number;
	smtpUser?: string;
	smtpPass?: string;
	smtpSecure?: boolean;
	googleOAuthClientId?: string;
	googleOAuthClientSecret?: string;
	googleOAuthCallbackUrl?: string;
}
