/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { FewShotExampleDto } from "./fewShotExampleDto";
import type { UpdateExtractorDtoConflictResolution } from "./updateExtractorDtoConflictResolution";
import type { UpdateExtractorDtoSchema } from "./updateExtractorDtoSchema";

export interface UpdateExtractorDto {
	/** The name of the extractor */
	name?: string;
	/** The description of the extractor */
	description?: string;
	thumbnailUrl?: string;
	schema?: UpdateExtractorDtoSchema;
	systemPrompt?: string;
	fewShotExamples?: FewShotExampleDto[];
	consensusEnabled?: boolean;
	/**
	 * @minimum 0
	 * @maximum 100
	 */
	confidenceThreshold?: number;
	conflictResolution?: UpdateExtractorDtoConflictResolution;
	citationEnabled?: boolean;
	citationIncludePdfPage?: boolean;
	citationIncludeBbox?: boolean;
	citationIncludeParagraphId?: boolean;
	contextWindow?: string;
	defaultModel?: string;
}
