/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { UpdateSchemaVariantDtoSchema } from "./updateSchemaVariantDtoSchema";

export interface UpdateSchemaVariantDto {
	name?: string;
	description?: string;
	schema?: UpdateSchemaVariantDtoSchema;
	isDefault?: boolean;
}
