/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { RunSourceDto } from "./runSourceDto";
import type { UpdateRunDtoExtractionProvider } from "./updateRunDtoExtractionProvider";
import type { UpdateRunDtoProcessingMode } from "./updateRunDtoProcessingMode";
import type { UpdateRunDtoSortConfig } from "./updateRunDtoSortConfig";

export interface UpdateRunDto {
	/** The ID of the extractor to use for this run */
	extractorId?: string;
	/** List of documents to process */
	sources?: RunSourceDto[];
	processingMode?: UpdateRunDtoProcessingMode;
	extractionProvider?: UpdateRunDtoExtractionProvider;
	/** ID of schema variant to use for extraction */
	variantId?: string;
	/** Field names to exclude from extraction */
	skippedFields?: string[];
	/** Reference sort configuration */
	sortConfig?: UpdateRunDtoSortConfig;
}
