/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { UserControllerFindAllRole } from "./userControllerFindAllRole";

export type UserControllerFindAllParams = {
	/**
	 * Filter users by their role
	 */
	role?: UserControllerFindAllRole;
	/**
	 * Filter users by their email address
	 */
	email?: string;
	/**
	 * Filter users by their email verification status
	 */
	isEmailVerified?: boolean;
	/**
	 * Search for users by a keyword
	 */
	search?: string;
};
