/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export interface VerifyEmailDto {
	/** The email address to be verified. */
	email: string;
	/** The one-time password (OTP) sent to the email for verification. */
	otp: string;
}
