/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { WorkflowConnectionDto } from "./workflowConnectionDto";
import type { WorkflowNodeDto } from "./workflowNodeDto";

export interface WorkflowDefinitionDto {
	nodes: WorkflowNodeDto[];
	connections: WorkflowConnectionDto[];
}
