/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import type { WorkflowNodeDtoParams } from "./workflowNodeDtoParams";
import type { WorkflowNodePositionDto } from "./workflowNodePositionDto";

export interface WorkflowNodeDto {
	id: string;
	type: string;
	position: WorkflowNodePositionDto;
	params: WorkflowNodeDtoParams;
}
