/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */

export interface WorkflowConnectionDto {
	id: string;
	source: string;
	target: string;
	sourceHandle?: string;
	targetHandle?: string;
}
