/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	AuthControllerInitiateEmailVerificationBody,
	AuthControllerSignUp201,
	AuthResponse,
	LoginDto,
	RefreshTokenDto,
	RefreshTokenResponse,
	ResetPasswordConfirmDto,
	ResetPasswordInitiateDto,
	SignUpDto,
	UpdateEmailDto,
	UpdatePasswordDto,
	VerifyEmailDto,
} from "../../models";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Register a new user
 */
export type authControllerSignUpResponse201 = {
	data: AuthControllerSignUp201;
	status: 201;
};

export type authControllerSignUpResponse409 = {
	data: void;
	status: 409;
};

export type authControllerSignUpResponseSuccess =
	authControllerSignUpResponse201 & {
		headers: Headers;
	};
export type authControllerSignUpResponseError =
	authControllerSignUpResponse409 & {
		headers: Headers;
	};

export type authControllerSignUpResponse =
	| authControllerSignUpResponseSuccess
	| authControllerSignUpResponseError;

export const getAuthControllerSignUpUrl = () => {
	return `/auth/signup`;
};

export const authControllerSignUp = async (
	signUpDto: SignUpDto,
	options?: RequestInit,
): Promise<authControllerSignUpResponse> => {
	return HttpClient<authControllerSignUpResponse>(
		getAuthControllerSignUpUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(signUpDto),
		},
	);
};

export const getAuthControllerSignUpMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerSignUp>>,
		TError,
		{ data: SignUpDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerSignUp>>,
	TError,
	{ data: SignUpDto },
	TContext
> => {
	const mutationKey = ["authControllerSignUp"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerSignUp>>,
		{ data: SignUpDto }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerSignUp(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignUpMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerSignUp>>
>;
export type AuthControllerSignUpMutationBody = SignUpDto;
export type AuthControllerSignUpMutationError = void;

/**
 * @summary Register a new user
 */
export const useAuthControllerSignUp = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerSignUp>>,
			TError,
			{ data: SignUpDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerSignUp>>,
	TError,
	{ data: SignUpDto },
	TContext
> => {
	return useMutation(
		getAuthControllerSignUpMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Authenticate user
 */
export type authControllerLoginResponse200 = {
	data: AuthResponse;
	status: 200;
};

export type authControllerLoginResponse401 = {
	data: void;
	status: 401;
};

export type authControllerLoginResponseSuccess =
	authControllerLoginResponse200 & {
		headers: Headers;
	};
export type authControllerLoginResponseError =
	authControllerLoginResponse401 & {
		headers: Headers;
	};

export type authControllerLoginResponse =
	| authControllerLoginResponseSuccess
	| authControllerLoginResponseError;

export const getAuthControllerLoginUrl = () => {
	return `/auth/login`;
};

export const authControllerLogin = async (
	loginDto: LoginDto,
	options?: RequestInit,
): Promise<authControllerLoginResponse> => {
	return HttpClient<authControllerLoginResponse>(getAuthControllerLoginUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(loginDto),
	});
};

export const getAuthControllerLoginMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerLogin>>,
		TError,
		{ data: LoginDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerLogin>>,
	TError,
	{ data: LoginDto },
	TContext
> => {
	const mutationKey = ["authControllerLogin"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerLogin>>,
		{ data: LoginDto }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerLogin(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerLogin>>
>;
export type AuthControllerLoginMutationBody = LoginDto;
export type AuthControllerLoginMutationError = void;

/**
 * @summary Authenticate user
 */
export const useAuthControllerLogin = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerLogin>>,
			TError,
			{ data: LoginDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerLogin>>,
	TError,
	{ data: LoginDto },
	TContext
> => {
	return useMutation(
		getAuthControllerLoginMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Refresh access token
 */
export type authControllerRefreshTokenResponse200 = {
	data: RefreshTokenResponse;
	status: 200;
};

export type authControllerRefreshTokenResponse401 = {
	data: void;
	status: 401;
};

export type authControllerRefreshTokenResponseSuccess =
	authControllerRefreshTokenResponse200 & {
		headers: Headers;
	};
export type authControllerRefreshTokenResponseError =
	authControllerRefreshTokenResponse401 & {
		headers: Headers;
	};

export type authControllerRefreshTokenResponse =
	| authControllerRefreshTokenResponseSuccess
	| authControllerRefreshTokenResponseError;

export const getAuthControllerRefreshTokenUrl = () => {
	return `/auth/refresh`;
};

export const authControllerRefreshToken = async (
	refreshTokenDto: RefreshTokenDto,
	options?: RequestInit,
): Promise<authControllerRefreshTokenResponse> => {
	return HttpClient<authControllerRefreshTokenResponse>(
		getAuthControllerRefreshTokenUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(refreshTokenDto),
		},
	);
};

export const getAuthControllerRefreshTokenMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerRefreshToken>>,
		TError,
		{ data: RefreshTokenDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerRefreshToken>>,
	TError,
	{ data: RefreshTokenDto },
	TContext
> => {
	const mutationKey = ["authControllerRefreshToken"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerRefreshToken>>,
		{ data: RefreshTokenDto }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerRefreshToken(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerRefreshTokenMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerRefreshToken>>
>;
export type AuthControllerRefreshTokenMutationBody = RefreshTokenDto;
export type AuthControllerRefreshTokenMutationError = void;

/**
 * @summary Refresh access token
 */
export const useAuthControllerRefreshToken = <
	TError = void,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerRefreshToken>>,
			TError,
			{ data: RefreshTokenDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerRefreshToken>>,
	TError,
	{ data: RefreshTokenDto },
	TContext
> => {
	return useMutation(
		getAuthControllerRefreshTokenMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Verify access and refresh tokens
 */
export type authControllerVerifyTokensResponse200 = {
	data: void;
	status: 200;
};

export type authControllerVerifyTokensResponse401 = {
	data: void;
	status: 401;
};

export type authControllerVerifyTokensResponseSuccess =
	authControllerVerifyTokensResponse200 & {
		headers: Headers;
	};
export type authControllerVerifyTokensResponseError =
	authControllerVerifyTokensResponse401 & {
		headers: Headers;
	};

export type authControllerVerifyTokensResponse =
	| authControllerVerifyTokensResponseSuccess
	| authControllerVerifyTokensResponseError;

export const getAuthControllerVerifyTokensUrl = () => {
	return `/auth/verify-tokens`;
};

export const authControllerVerifyTokens = async (
	options?: RequestInit,
): Promise<authControllerVerifyTokensResponse> => {
	return HttpClient<authControllerVerifyTokensResponse>(
		getAuthControllerVerifyTokensUrl(),
		{
			...options,
			method: "POST",
		},
	);
};

export const getAuthControllerVerifyTokensMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerVerifyTokens>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerVerifyTokens>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["authControllerVerifyTokens"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerVerifyTokens>>,
		void
	> = () => {
		return authControllerVerifyTokens(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerVerifyTokensMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerVerifyTokens>>
>;

export type AuthControllerVerifyTokensMutationError = void;

/**
 * @summary Verify access and refresh tokens
 */
export const useAuthControllerVerifyTokens = <
	TError = void,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerVerifyTokens>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerVerifyTokens>>,
	TError,
	void,
	TContext
> => {
	return useMutation(
		getAuthControllerVerifyTokensMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Initiate password reset
 */
export type authControllerForgotPasswordResponse202 = {
	data: void;
	status: 202;
};

export type authControllerForgotPasswordResponseSuccess =
	authControllerForgotPasswordResponse202 & {
		headers: Headers;
	};

export type authControllerForgotPasswordResponse =
	authControllerForgotPasswordResponseSuccess;

export const getAuthControllerForgotPasswordUrl = () => {
	return `/auth/password/forgot`;
};

export const authControllerForgotPassword = async (
	resetPasswordInitiateDto: ResetPasswordInitiateDto,
	options?: RequestInit,
): Promise<authControllerForgotPasswordResponse> => {
	return HttpClient<authControllerForgotPasswordResponse>(
		getAuthControllerForgotPasswordUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(resetPasswordInitiateDto),
		},
	);
};

export const getAuthControllerForgotPasswordMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerForgotPassword>>,
		TError,
		{ data: ResetPasswordInitiateDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerForgotPassword>>,
	TError,
	{ data: ResetPasswordInitiateDto },
	TContext
> => {
	const mutationKey = ["authControllerForgotPassword"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerForgotPassword>>,
		{ data: ResetPasswordInitiateDto }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerForgotPassword(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerForgotPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerForgotPassword>>
>;
export type AuthControllerForgotPasswordMutationBody = ResetPasswordInitiateDto;
export type AuthControllerForgotPasswordMutationError = unknown;

/**
 * @summary Initiate password reset
 */
export const useAuthControllerForgotPassword = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerForgotPassword>>,
			TError,
			{ data: ResetPasswordInitiateDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerForgotPassword>>,
	TError,
	{ data: ResetPasswordInitiateDto },
	TContext
> => {
	return useMutation(
		getAuthControllerForgotPasswordMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Confirm password reset
 */
export type authControllerResetPasswordResponse200 = {
	data: void;
	status: 200;
};

export type authControllerResetPasswordResponse401 = {
	data: void;
	status: 401;
};

export type authControllerResetPasswordResponseSuccess =
	authControllerResetPasswordResponse200 & {
		headers: Headers;
	};
export type authControllerResetPasswordResponseError =
	authControllerResetPasswordResponse401 & {
		headers: Headers;
	};

export type authControllerResetPasswordResponse =
	| authControllerResetPasswordResponseSuccess
	| authControllerResetPasswordResponseError;

export const getAuthControllerResetPasswordUrl = () => {
	return `/auth/password/reset`;
};

export const authControllerResetPassword = async (
	resetPasswordConfirmDto: ResetPasswordConfirmDto,
	options?: RequestInit,
): Promise<authControllerResetPasswordResponse> => {
	return HttpClient<authControllerResetPasswordResponse>(
		getAuthControllerResetPasswordUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(resetPasswordConfirmDto),
		},
	);
};

export const getAuthControllerResetPasswordMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerResetPassword>>,
		TError,
		{ data: ResetPasswordConfirmDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerResetPassword>>,
	TError,
	{ data: ResetPasswordConfirmDto },
	TContext
> => {
	const mutationKey = ["authControllerResetPassword"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerResetPassword>>,
		{ data: ResetPasswordConfirmDto }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerResetPassword(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerResetPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerResetPassword>>
>;
export type AuthControllerResetPasswordMutationBody = ResetPasswordConfirmDto;
export type AuthControllerResetPasswordMutationError = void;

/**
 * @summary Confirm password reset
 */
export const useAuthControllerResetPassword = <
	TError = void,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerResetPassword>>,
			TError,
			{ data: ResetPasswordConfirmDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerResetPassword>>,
	TError,
	{ data: ResetPasswordConfirmDto },
	TContext
> => {
	return useMutation(
		getAuthControllerResetPasswordMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Update password (authenticated users)
 */
export type authControllerUpdatePasswordResponse200 = {
	data: void;
	status: 200;
};

export type authControllerUpdatePasswordResponse401 = {
	data: void;
	status: 401;
};

export type authControllerUpdatePasswordResponseSuccess =
	authControllerUpdatePasswordResponse200 & {
		headers: Headers;
	};
export type authControllerUpdatePasswordResponseError =
	authControllerUpdatePasswordResponse401 & {
		headers: Headers;
	};

export type authControllerUpdatePasswordResponse =
	| authControllerUpdatePasswordResponseSuccess
	| authControllerUpdatePasswordResponseError;

export const getAuthControllerUpdatePasswordUrl = () => {
	return `/auth/password/update`;
};

export const authControllerUpdatePassword = async (
	updatePasswordDto: UpdatePasswordDto,
	options?: RequestInit,
): Promise<authControllerUpdatePasswordResponse> => {
	return HttpClient<authControllerUpdatePasswordResponse>(
		getAuthControllerUpdatePasswordUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(updatePasswordDto),
		},
	);
};

export const getAuthControllerUpdatePasswordMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerUpdatePassword>>,
		TError,
		{ data: UpdatePasswordDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerUpdatePassword>>,
	TError,
	{ data: UpdatePasswordDto },
	TContext
> => {
	const mutationKey = ["authControllerUpdatePassword"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerUpdatePassword>>,
		{ data: UpdatePasswordDto }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerUpdatePassword(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerUpdatePasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerUpdatePassword>>
>;
export type AuthControllerUpdatePasswordMutationBody = UpdatePasswordDto;
export type AuthControllerUpdatePasswordMutationError = void;

/**
 * @summary Update password (authenticated users)
 */
export const useAuthControllerUpdatePassword = <
	TError = void,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerUpdatePassword>>,
			TError,
			{ data: UpdatePasswordDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerUpdatePassword>>,
	TError,
	{ data: UpdatePasswordDto },
	TContext
> => {
	return useMutation(
		getAuthControllerUpdatePasswordMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Update email address
 */
export type authControllerUpdateEmailResponse200 = {
	data: void;
	status: 200;
};

export type authControllerUpdateEmailResponse409 = {
	data: void;
	status: 409;
};

export type authControllerUpdateEmailResponseSuccess =
	authControllerUpdateEmailResponse200 & {
		headers: Headers;
	};
export type authControllerUpdateEmailResponseError =
	authControllerUpdateEmailResponse409 & {
		headers: Headers;
	};

export type authControllerUpdateEmailResponse =
	| authControllerUpdateEmailResponseSuccess
	| authControllerUpdateEmailResponseError;

export const getAuthControllerUpdateEmailUrl = () => {
	return `/auth/email/update`;
};

export const authControllerUpdateEmail = async (
	updateEmailDto: UpdateEmailDto,
	options?: RequestInit,
): Promise<authControllerUpdateEmailResponse> => {
	return HttpClient<authControllerUpdateEmailResponse>(
		getAuthControllerUpdateEmailUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(updateEmailDto),
		},
	);
};

export const getAuthControllerUpdateEmailMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerUpdateEmail>>,
		TError,
		{ data: UpdateEmailDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerUpdateEmail>>,
	TError,
	{ data: UpdateEmailDto },
	TContext
> => {
	const mutationKey = ["authControllerUpdateEmail"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerUpdateEmail>>,
		{ data: UpdateEmailDto }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerUpdateEmail(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerUpdateEmailMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerUpdateEmail>>
>;
export type AuthControllerUpdateEmailMutationBody = UpdateEmailDto;
export type AuthControllerUpdateEmailMutationError = void;

/**
 * @summary Update email address
 */
export const useAuthControllerUpdateEmail = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerUpdateEmail>>,
			TError,
			{ data: UpdateEmailDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerUpdateEmail>>,
	TError,
	{ data: UpdateEmailDto },
	TContext
> => {
	return useMutation(
		getAuthControllerUpdateEmailMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Verify email address
 */
export type authControllerVerifyEmailResponse200 = {
	data: AuthResponse;
	status: 200;
};

export type authControllerVerifyEmailResponse400 = {
	data: void;
	status: 400;
};

export type authControllerVerifyEmailResponseSuccess =
	authControllerVerifyEmailResponse200 & {
		headers: Headers;
	};
export type authControllerVerifyEmailResponseError =
	authControllerVerifyEmailResponse400 & {
		headers: Headers;
	};

export type authControllerVerifyEmailResponse =
	| authControllerVerifyEmailResponseSuccess
	| authControllerVerifyEmailResponseError;

export const getAuthControllerVerifyEmailUrl = () => {
	return `/auth/email/verify`;
};

export const authControllerVerifyEmail = async (
	verifyEmailDto: VerifyEmailDto,
	options?: RequestInit,
): Promise<authControllerVerifyEmailResponse> => {
	return HttpClient<authControllerVerifyEmailResponse>(
		getAuthControllerVerifyEmailUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(verifyEmailDto),
		},
	);
};

export const getAuthControllerVerifyEmailMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerVerifyEmail>>,
		TError,
		{ data: VerifyEmailDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerVerifyEmail>>,
	TError,
	{ data: VerifyEmailDto },
	TContext
> => {
	const mutationKey = ["authControllerVerifyEmail"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerVerifyEmail>>,
		{ data: VerifyEmailDto }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerVerifyEmail(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerVerifyEmailMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerVerifyEmail>>
>;
export type AuthControllerVerifyEmailMutationBody = VerifyEmailDto;
export type AuthControllerVerifyEmailMutationError = void;

/**
 * @summary Verify email address
 */
export const useAuthControllerVerifyEmail = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerVerifyEmail>>,
			TError,
			{ data: VerifyEmailDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerVerifyEmail>>,
	TError,
	{ data: VerifyEmailDto },
	TContext
> => {
	return useMutation(
		getAuthControllerVerifyEmailMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Initiate email verification
 */
export type authControllerInitiateEmailVerificationResponse200 = {
	data: void;
	status: 200;
};

export type authControllerInitiateEmailVerificationResponse400 = {
	data: void;
	status: 400;
};

export type authControllerInitiateEmailVerificationResponseSuccess =
	authControllerInitiateEmailVerificationResponse200 & {
		headers: Headers;
	};
export type authControllerInitiateEmailVerificationResponseError =
	authControllerInitiateEmailVerificationResponse400 & {
		headers: Headers;
	};

export type authControllerInitiateEmailVerificationResponse =
	| authControllerInitiateEmailVerificationResponseSuccess
	| authControllerInitiateEmailVerificationResponseError;

export const getAuthControllerInitiateEmailVerificationUrl = () => {
	return `/auth/email/verify/initiate`;
};

export const authControllerInitiateEmailVerification = async (
	authControllerInitiateEmailVerificationBody: AuthControllerInitiateEmailVerificationBody,
	options?: RequestInit,
): Promise<authControllerInitiateEmailVerificationResponse> => {
	return HttpClient<authControllerInitiateEmailVerificationResponse>(
		getAuthControllerInitiateEmailVerificationUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(authControllerInitiateEmailVerificationBody),
		},
	);
};

export const getAuthControllerInitiateEmailVerificationMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authControllerInitiateEmailVerification>>,
		TError,
		{ data: AuthControllerInitiateEmailVerificationBody },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authControllerInitiateEmailVerification>>,
	TError,
	{ data: AuthControllerInitiateEmailVerificationBody },
	TContext
> => {
	const mutationKey = ["authControllerInitiateEmailVerification"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authControllerInitiateEmailVerification>>,
		{ data: AuthControllerInitiateEmailVerificationBody }
	> = (props) => {
		const { data } = props ?? {};

		return authControllerInitiateEmailVerification(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthControllerInitiateEmailVerificationMutationResult = NonNullable<
	Awaited<ReturnType<typeof authControllerInitiateEmailVerification>>
>;
export type AuthControllerInitiateEmailVerificationMutationBody =
	AuthControllerInitiateEmailVerificationBody;
export type AuthControllerInitiateEmailVerificationMutationError = void;

/**
 * @summary Initiate email verification
 */
export const useAuthControllerInitiateEmailVerification = <
	TError = void,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authControllerInitiateEmailVerification>>,
			TError,
			{ data: AuthControllerInitiateEmailVerificationBody },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authControllerInitiateEmailVerification>>,
	TError,
	{ data: AuthControllerInitiateEmailVerificationBody },
	TContext
> => {
	return useMutation(
		getAuthControllerInitiateEmailVerificationMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Initiate Google OAuth login
 */
export type authControllerGoogleAuthResponse200 = {
	data: void;
	status: 200;
};

export type authControllerGoogleAuthResponseSuccess =
	authControllerGoogleAuthResponse200 & {
		headers: Headers;
	};

export type authControllerGoogleAuthResponse =
	authControllerGoogleAuthResponseSuccess;

export const getAuthControllerGoogleAuthUrl = () => {
	return `/auth/google`;
};

export const authControllerGoogleAuth = async (
	options?: RequestInit,
): Promise<authControllerGoogleAuthResponse> => {
	return HttpClient<authControllerGoogleAuthResponse>(
		getAuthControllerGoogleAuthUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getAuthControllerGoogleAuthQueryKey = () => {
	return [`/auth/google`] as const;
};

export const getAuthControllerGoogleAuthQueryOptions = <
	TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof authControllerGoogleAuth>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getAuthControllerGoogleAuthQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof authControllerGoogleAuth>>
	> = ({ signal }) => authControllerGoogleAuth({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authControllerGoogleAuth>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGoogleAuthQueryResult = NonNullable<
	Awaited<ReturnType<typeof authControllerGoogleAuth>>
>;
export type AuthControllerGoogleAuthQueryError = unknown;

export function useAuthControllerGoogleAuth<
	TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof authControllerGoogleAuth>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGoogleAuth>>,
					TError,
					Awaited<ReturnType<typeof authControllerGoogleAuth>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGoogleAuth<
	TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof authControllerGoogleAuth>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGoogleAuth>>,
					TError,
					Awaited<ReturnType<typeof authControllerGoogleAuth>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGoogleAuth<
	TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof authControllerGoogleAuth>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Initiate Google OAuth login
 */

export function useAuthControllerGoogleAuth<
	TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof authControllerGoogleAuth>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getAuthControllerGoogleAuthQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type authControllerGoogleAuthRedirectResponse200 = {
	data: void;
	status: 200;
};

export type authControllerGoogleAuthRedirectResponseSuccess =
	authControllerGoogleAuthRedirectResponse200 & {
		headers: Headers;
	};

export type authControllerGoogleAuthRedirectResponse =
	authControllerGoogleAuthRedirectResponseSuccess;

export const getAuthControllerGoogleAuthRedirectUrl = () => {
	return `/auth/google/callback`;
};

export const authControllerGoogleAuthRedirect = async (
	options?: RequestInit,
): Promise<authControllerGoogleAuthRedirectResponse> => {
	return HttpClient<authControllerGoogleAuthRedirectResponse>(
		getAuthControllerGoogleAuthRedirectUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getAuthControllerGoogleAuthRedirectQueryKey = () => {
	return [`/auth/google/callback`] as const;
};

export const getAuthControllerGoogleAuthRedirectQueryOptions = <
	TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getAuthControllerGoogleAuthRedirectQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>
	> = ({ signal }) =>
		authControllerGoogleAuthRedirect({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGoogleAuthRedirectQueryResult = NonNullable<
	Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>
>;
export type AuthControllerGoogleAuthRedirectQueryError = unknown;

export function useAuthControllerGoogleAuthRedirect<
	TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
					TError,
					Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGoogleAuthRedirect<
	TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
					TError,
					Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGoogleAuthRedirect<
	TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAuthControllerGoogleAuthRedirect<
	TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getAuthControllerGoogleAuthRedirectQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
