/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const LlmControllerListModelsResponseItem = zod.object({
  "id": zod.string(),
  "owned_by": zod.string()
})
export const LlmControllerListModelsResponse = zod.array(LlmControllerListModelsResponseItem)

