/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Create a new workflow
 */
export const WorkflowsControllerCreateBody = zod.object({
  "name": zod.string(),
  "description": zod.string().optional(),
  "definition": zod.object({
  "nodes": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "position": zod.object({
  "x": zod.number(),
  "y": zod.number()
}),
  "params": zod.record(zod.string(), zod.unknown())
})),
  "connections": zod.array(zod.object({
  "id": zod.string(),
  "source": zod.string(),
  "target": zod.string(),
  "sourceHandle": zod.string().optional(),
  "targetHandle": zod.string().optional()
}))
}).optional(),
  "triggerConfig": zod.object({
  "type": zod.enum(['webhook', 'email', 'schedule', 'google_drive', 's3']),
  "webhookPath": zod.string().optional(),
  "imapConfig": zod.object({
  "host": zod.string(),
  "port": zod.number(),
  "user": zod.string(),
  "password": zod.string(),
  "folder": zod.string(),
  "filterSubject": zod.string().optional(),
  "filterFrom": zod.string().optional()
}).optional(),
  "cronExpression": zod.string().optional(),
  "timezone": zod.string().optional()
}).optional()
})

/**
 * @summary Get a specific workflow
 */
export const WorkflowsControllerFindOneParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Update a workflow
 */
export const WorkflowsControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const WorkflowsControllerUpdateBody = zod.object({
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "definition": zod.object({
  "nodes": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "position": zod.object({
  "x": zod.number(),
  "y": zod.number()
}),
  "params": zod.record(zod.string(), zod.unknown())
})),
  "connections": zod.array(zod.object({
  "id": zod.string(),
  "source": zod.string(),
  "target": zod.string(),
  "sourceHandle": zod.string().optional(),
  "targetHandle": zod.string().optional()
}))
}).optional(),
  "triggerConfig": zod.object({
  "type": zod.enum(['webhook', 'email', 'schedule', 'google_drive', 's3']),
  "webhookPath": zod.string().optional(),
  "imapConfig": zod.object({
  "host": zod.string(),
  "port": zod.number(),
  "user": zod.string(),
  "password": zod.string(),
  "folder": zod.string(),
  "filterSubject": zod.string().optional(),
  "filterFrom": zod.string().optional()
}).optional(),
  "cronExpression": zod.string().optional(),
  "timezone": zod.string().optional()
}).optional()
})

/**
 * @summary Delete a workflow
 */
export const WorkflowsControllerRemoveParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Activate a workflow
 */
export const WorkflowsControllerActivateParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Pause a workflow
 */
export const WorkflowsControllerPauseParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Get execution history for a workflow
 */
export const WorkflowsControllerGetExecutionsParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Manually trigger a workflow
 */
export const WorkflowsControllerTriggerParams = zod.object({
  "id": zod.string()
})

