/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	CreateRunDto,
	RunsControllerFindAllParams,
	UpdateRunDto,
} from "../../models";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new extraction run
 */
export type runsControllerCreateResponse201 = {
	data: void;
	status: 201;
};

export type runsControllerCreateResponseSuccess =
	runsControllerCreateResponse201 & {
		headers: Headers;
	};

export type runsControllerCreateResponse = runsControllerCreateResponseSuccess;

export const getRunsControllerCreateUrl = () => {
	return `/runs`;
};

export const runsControllerCreate = async (
	createRunDto: CreateRunDto,
	options?: RequestInit,
): Promise<runsControllerCreateResponse> => {
	return HttpClient<runsControllerCreateResponse>(
		getRunsControllerCreateUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(createRunDto),
		},
	);
};

export const getRunsControllerCreateMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof runsControllerCreate>>,
		TError,
		{ data: CreateRunDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof runsControllerCreate>>,
	TError,
	{ data: CreateRunDto },
	TContext
> => {
	const mutationKey = ["runsControllerCreate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof runsControllerCreate>>,
		{ data: CreateRunDto }
	> = (props) => {
		const { data } = props ?? {};

		return runsControllerCreate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RunsControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof runsControllerCreate>>
>;
export type RunsControllerCreateMutationBody = CreateRunDto;
export type RunsControllerCreateMutationError = unknown;

/**
 * @summary Create a new extraction run
 */
export const useRunsControllerCreate = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof runsControllerCreate>>,
			TError,
			{ data: CreateRunDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof runsControllerCreate>>,
	TError,
	{ data: CreateRunDto },
	TContext
> => {
	return useMutation(
		getRunsControllerCreateMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Get all runs with pagination and filtering
 */
export type runsControllerFindAllResponse200 = {
	data: void;
	status: 200;
};

export type runsControllerFindAllResponseSuccess =
	runsControllerFindAllResponse200 & {
		headers: Headers;
	};

export type runsControllerFindAllResponse =
	runsControllerFindAllResponseSuccess;

export const getRunsControllerFindAllUrl = (
	params?: RunsControllerFindAllParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0 ? `/runs?${stringifiedParams}` : `/runs`;
};

export const runsControllerFindAll = async (
	params?: RunsControllerFindAllParams,
	options?: RequestInit,
): Promise<runsControllerFindAllResponse> => {
	return HttpClient<runsControllerFindAllResponse>(
		getRunsControllerFindAllUrl(params),
		{
			...options,
			method: "GET",
		},
	);
};

export const getRunsControllerFindAllQueryKey = (
	params?: RunsControllerFindAllParams,
) => {
	return [`/runs`, ...(params ? [params] : [])] as const;
};

export const getRunsControllerFindAllQueryOptions = <
	TData = Awaited<ReturnType<typeof runsControllerFindAll>>,
	TError = unknown,
>(
	params?: RunsControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRunsControllerFindAllQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof runsControllerFindAll>>
	> = ({ signal }) =>
		runsControllerFindAll(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof runsControllerFindAll>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RunsControllerFindAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof runsControllerFindAll>>
>;
export type RunsControllerFindAllQueryError = unknown;

export function useRunsControllerFindAll<
	TData = Awaited<ReturnType<typeof runsControllerFindAll>>,
	TError = unknown,
>(
	params: undefined | RunsControllerFindAllParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindAll>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof runsControllerFindAll>>,
					TError,
					Awaited<ReturnType<typeof runsControllerFindAll>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRunsControllerFindAll<
	TData = Awaited<ReturnType<typeof runsControllerFindAll>>,
	TError = unknown,
>(
	params?: RunsControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindAll>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof runsControllerFindAll>>,
					TError,
					Awaited<ReturnType<typeof runsControllerFindAll>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRunsControllerFindAll<
	TData = Awaited<ReturnType<typeof runsControllerFindAll>>,
	TError = unknown,
>(
	params?: RunsControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all runs with pagination and filtering
 */

export function useRunsControllerFindAll<
	TData = Awaited<ReturnType<typeof runsControllerFindAll>>,
	TError = unknown,
>(
	params?: RunsControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindAll>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getRunsControllerFindAllQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a single run by ID
 */
export type runsControllerFindOneResponse200 = {
	data: void;
	status: 200;
};

export type runsControllerFindOneResponse404 = {
	data: void;
	status: 404;
};

export type runsControllerFindOneResponseSuccess =
	runsControllerFindOneResponse200 & {
		headers: Headers;
	};
export type runsControllerFindOneResponseError =
	runsControllerFindOneResponse404 & {
		headers: Headers;
	};

export type runsControllerFindOneResponse =
	| runsControllerFindOneResponseSuccess
	| runsControllerFindOneResponseError;

export const getRunsControllerFindOneUrl = (id: string) => {
	return `/runs/${id}`;
};

export const runsControllerFindOne = async (
	id: string,
	options?: RequestInit,
): Promise<runsControllerFindOneResponse> => {
	return HttpClient<runsControllerFindOneResponse>(
		getRunsControllerFindOneUrl(id),
		{
			...options,
			method: "GET",
		},
	);
};

export const getRunsControllerFindOneQueryKey = (id: string) => {
	return [`/runs/${id}`] as const;
};

export const getRunsControllerFindOneQueryOptions = <
	TData = Awaited<ReturnType<typeof runsControllerFindOne>>,
	TError = void,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindOne>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getRunsControllerFindOneQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof runsControllerFindOne>>
	> = ({ signal }) => runsControllerFindOne(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof runsControllerFindOne>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RunsControllerFindOneQueryResult = NonNullable<
	Awaited<ReturnType<typeof runsControllerFindOne>>
>;
export type RunsControllerFindOneQueryError = void;

export function useRunsControllerFindOne<
	TData = Awaited<ReturnType<typeof runsControllerFindOne>>,
	TError = void,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindOne>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof runsControllerFindOne>>,
					TError,
					Awaited<ReturnType<typeof runsControllerFindOne>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRunsControllerFindOne<
	TData = Awaited<ReturnType<typeof runsControllerFindOne>>,
	TError = void,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindOne>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof runsControllerFindOne>>,
					TError,
					Awaited<ReturnType<typeof runsControllerFindOne>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRunsControllerFindOne<
	TData = Awaited<ReturnType<typeof runsControllerFindOne>>,
	TError = void,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindOne>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a single run by ID
 */

export function useRunsControllerFindOne<
	TData = Awaited<ReturnType<typeof runsControllerFindOne>>,
	TError = void,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof runsControllerFindOne>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getRunsControllerFindOneQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a run
 */
export type runsControllerUpdateResponse200 = {
	data: void;
	status: 200;
};

export type runsControllerUpdateResponseSuccess =
	runsControllerUpdateResponse200 & {
		headers: Headers;
	};

export type runsControllerUpdateResponse = runsControllerUpdateResponseSuccess;

export const getRunsControllerUpdateUrl = (id: string) => {
	return `/runs/${id}`;
};

export const runsControllerUpdate = async (
	id: string,
	updateRunDto: UpdateRunDto,
	options?: RequestInit,
): Promise<runsControllerUpdateResponse> => {
	return HttpClient<runsControllerUpdateResponse>(
		getRunsControllerUpdateUrl(id),
		{
			...options,
			method: "PATCH",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(updateRunDto),
		},
	);
};

export const getRunsControllerUpdateMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof runsControllerUpdate>>,
		TError,
		{ id: string; data: UpdateRunDto },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof runsControllerUpdate>>,
	TError,
	{ id: string; data: UpdateRunDto },
	TContext
> => {
	const mutationKey = ["runsControllerUpdate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof runsControllerUpdate>>,
		{ id: string; data: UpdateRunDto }
	> = (props) => {
		const { id, data } = props ?? {};

		return runsControllerUpdate(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RunsControllerUpdateMutationResult = NonNullable<
	Awaited<ReturnType<typeof runsControllerUpdate>>
>;
export type RunsControllerUpdateMutationBody = UpdateRunDto;
export type RunsControllerUpdateMutationError = unknown;

/**
 * @summary Update a run
 */
export const useRunsControllerUpdate = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof runsControllerUpdate>>,
			TError,
			{ id: string; data: UpdateRunDto },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof runsControllerUpdate>>,
	TError,
	{ id: string; data: UpdateRunDto },
	TContext
> => {
	return useMutation(
		getRunsControllerUpdateMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Delete a run
 */
export type runsControllerRemoveResponse200 = {
	data: void;
	status: 200;
};

export type runsControllerRemoveResponseSuccess =
	runsControllerRemoveResponse200 & {
		headers: Headers;
	};

export type runsControllerRemoveResponse = runsControllerRemoveResponseSuccess;

export const getRunsControllerRemoveUrl = (id: string) => {
	return `/runs/${id}`;
};

export const runsControllerRemove = async (
	id: string,
	options?: RequestInit,
): Promise<runsControllerRemoveResponse> => {
	return HttpClient<runsControllerRemoveResponse>(
		getRunsControllerRemoveUrl(id),
		{
			...options,
			method: "DELETE",
		},
	);
};

export const getRunsControllerRemoveMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof runsControllerRemove>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof runsControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["runsControllerRemove"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof runsControllerRemove>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return runsControllerRemove(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RunsControllerRemoveMutationResult = NonNullable<
	Awaited<ReturnType<typeof runsControllerRemove>>
>;

export type RunsControllerRemoveMutationError = unknown;

/**
 * @summary Delete a run
 */
export const useRunsControllerRemove = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof runsControllerRemove>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof runsControllerRemove>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getRunsControllerRemoveMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Retry a failed or cancelled run
 */
export type runsControllerRetryResponse200 = {
	data: void;
	status: 200;
};

export type runsControllerRetryResponse404 = {
	data: void;
	status: 404;
};

export type runsControllerRetryResponseSuccess =
	runsControllerRetryResponse200 & {
		headers: Headers;
	};
export type runsControllerRetryResponseError =
	runsControllerRetryResponse404 & {
		headers: Headers;
	};

export type runsControllerRetryResponse =
	| runsControllerRetryResponseSuccess
	| runsControllerRetryResponseError;

export const getRunsControllerRetryUrl = (id: string) => {
	return `/runs/${id}/retry`;
};

export const runsControllerRetry = async (
	id: string,
	options?: RequestInit,
): Promise<runsControllerRetryResponse> => {
	return HttpClient<runsControllerRetryResponse>(
		getRunsControllerRetryUrl(id),
		{
			...options,
			method: "POST",
		},
	);
};

export const getRunsControllerRetryMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof runsControllerRetry>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof runsControllerRetry>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["runsControllerRetry"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof runsControllerRetry>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return runsControllerRetry(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RunsControllerRetryMutationResult = NonNullable<
	Awaited<ReturnType<typeof runsControllerRetry>>
>;

export type RunsControllerRetryMutationError = void;

/**
 * @summary Retry a failed or cancelled run
 */
export const useRunsControllerRetry = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof runsControllerRetry>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof runsControllerRetry>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getRunsControllerRetryMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Retry a single failed source within a run
 */
export type runsControllerRetrySourceResponse200 = {
	data: void;
	status: 200;
};

export type runsControllerRetrySourceResponse400 = {
	data: void;
	status: 400;
};

export type runsControllerRetrySourceResponse404 = {
	data: void;
	status: 404;
};

export type runsControllerRetrySourceResponseSuccess =
	runsControllerRetrySourceResponse200 & {
		headers: Headers;
	};
export type runsControllerRetrySourceResponseError = (
	| runsControllerRetrySourceResponse400
	| runsControllerRetrySourceResponse404
) & {
	headers: Headers;
};

export type runsControllerRetrySourceResponse =
	| runsControllerRetrySourceResponseSuccess
	| runsControllerRetrySourceResponseError;

export const getRunsControllerRetrySourceUrl = (
	id: string,
	sourceId: string,
) => {
	return `/runs/${id}/sources/${sourceId}/retry`;
};

export const runsControllerRetrySource = async (
	id: string,
	sourceId: string,
	options?: RequestInit,
): Promise<runsControllerRetrySourceResponse> => {
	return HttpClient<runsControllerRetrySourceResponse>(
		getRunsControllerRetrySourceUrl(id, sourceId),
		{
			...options,
			method: "POST",
		},
	);
};

export const getRunsControllerRetrySourceMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof runsControllerRetrySource>>,
		TError,
		{ id: string; sourceId: string },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof runsControllerRetrySource>>,
	TError,
	{ id: string; sourceId: string },
	TContext
> => {
	const mutationKey = ["runsControllerRetrySource"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof runsControllerRetrySource>>,
		{ id: string; sourceId: string }
	> = (props) => {
		const { id, sourceId } = props ?? {};

		return runsControllerRetrySource(id, sourceId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RunsControllerRetrySourceMutationResult = NonNullable<
	Awaited<ReturnType<typeof runsControllerRetrySource>>
>;

export type RunsControllerRetrySourceMutationError = void;

/**
 * @summary Retry a single failed source within a run
 */
export const useRunsControllerRetrySource = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof runsControllerRetrySource>>,
			TError,
			{ id: string; sourceId: string },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof runsControllerRetrySource>>,
	TError,
	{ id: string; sourceId: string },
	TContext
> => {
	return useMutation(
		getRunsControllerRetrySourceMutationOptions(options),
		queryClient,
	);
};
