/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * docXtractor
 * A comprehensive docXtractor System to extract text from documents.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	FilesControllerConfirmFilesBody,
	FilesControllerGetFile200,
	FilesControllerListFiles200Item,
	FilesControllerUploadFile201,
	FilesControllerUploadFileBody,
	FilesControllerUploadMultipleFiles201Item,
	FilesControllerUploadMultipleFilesBody,
} from "../../models";

import { HttpClient } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Upload a file with user-scoped security. Files are encrypted at rest (SSE-S3) and isolated per user. Returns file ID, URL, and storage key for referencing in other CRUD operations.
 * @summary Upload a single file
 */
export type filesControllerUploadFileResponse201 = {
	data: FilesControllerUploadFile201;
	status: 201;
};

export type filesControllerUploadFileResponse400 = {
	data: void;
	status: 400;
};

export type filesControllerUploadFileResponseSuccess =
	filesControllerUploadFileResponse201 & {
		headers: Headers;
	};
export type filesControllerUploadFileResponseError =
	filesControllerUploadFileResponse400 & {
		headers: Headers;
	};

export type filesControllerUploadFileResponse =
	| filesControllerUploadFileResponseSuccess
	| filesControllerUploadFileResponseError;

export const getFilesControllerUploadFileUrl = () => {
	return `/files/upload`;
};

export const filesControllerUploadFile = async (
	filesControllerUploadFileBody: FilesControllerUploadFileBody,
	options?: RequestInit,
): Promise<filesControllerUploadFileResponse> => {
	const formData = new FormData();
	formData.append(`file`, filesControllerUploadFileBody.file);
	formData.append(`userId`, filesControllerUploadFileBody.userId);
	if (filesControllerUploadFileBody.metadata !== undefined) {
		formData.append(`metadata`, filesControllerUploadFileBody.metadata);
	}

	return HttpClient<filesControllerUploadFileResponse>(
		getFilesControllerUploadFileUrl(),
		{
			...options,
			method: "POST",
			body: formData,
		},
	);
};

export const getFilesControllerUploadFileMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof filesControllerUploadFile>>,
		TError,
		{ data: FilesControllerUploadFileBody },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof filesControllerUploadFile>>,
	TError,
	{ data: FilesControllerUploadFileBody },
	TContext
> => {
	const mutationKey = ["filesControllerUploadFile"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof filesControllerUploadFile>>,
		{ data: FilesControllerUploadFileBody }
	> = (props) => {
		const { data } = props ?? {};

		return filesControllerUploadFile(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type FilesControllerUploadFileMutationResult = NonNullable<
	Awaited<ReturnType<typeof filesControllerUploadFile>>
>;
export type FilesControllerUploadFileMutationBody =
	FilesControllerUploadFileBody;
export type FilesControllerUploadFileMutationError = void;

/**
 * @summary Upload a single file
 */
export const useFilesControllerUploadFile = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof filesControllerUploadFile>>,
			TError,
			{ data: FilesControllerUploadFileBody },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof filesControllerUploadFile>>,
	TError,
	{ data: FilesControllerUploadFileBody },
	TContext
> => {
	return useMutation(
		getFilesControllerUploadFileMutationOptions(options),
		queryClient,
	);
};
/**
 * Upload up to 10 files in a single request. All files are user-scoped and encrypted at rest. Returns an array of file references.
 * @summary Upload multiple files at once
 */
export type filesControllerUploadMultipleFilesResponse201 = {
	data: FilesControllerUploadMultipleFiles201Item[];
	status: 201;
};

export type filesControllerUploadMultipleFilesResponse400 = {
	data: void;
	status: 400;
};

export type filesControllerUploadMultipleFilesResponseSuccess =
	filesControllerUploadMultipleFilesResponse201 & {
		headers: Headers;
	};
export type filesControllerUploadMultipleFilesResponseError =
	filesControllerUploadMultipleFilesResponse400 & {
		headers: Headers;
	};

export type filesControllerUploadMultipleFilesResponse =
	| filesControllerUploadMultipleFilesResponseSuccess
	| filesControllerUploadMultipleFilesResponseError;

export const getFilesControllerUploadMultipleFilesUrl = () => {
	return `/files/upload-multiple`;
};

export const filesControllerUploadMultipleFiles = async (
	filesControllerUploadMultipleFilesBody: FilesControllerUploadMultipleFilesBody,
	options?: RequestInit,
): Promise<filesControllerUploadMultipleFilesResponse> => {
	const formData = new FormData();
	filesControllerUploadMultipleFilesBody.files.forEach((value) =>
		formData.append(`files`, value),
	);
	formData.append(`userId`, filesControllerUploadMultipleFilesBody.userId);
	if (filesControllerUploadMultipleFilesBody.metadata !== undefined) {
		formData.append(
			`metadata`,
			filesControllerUploadMultipleFilesBody.metadata,
		);
	}

	return HttpClient<filesControllerUploadMultipleFilesResponse>(
		getFilesControllerUploadMultipleFilesUrl(),
		{
			...options,
			method: "POST",
			body: formData,
		},
	);
};

export const getFilesControllerUploadMultipleFilesMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof filesControllerUploadMultipleFiles>>,
		TError,
		{ data: FilesControllerUploadMultipleFilesBody },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof filesControllerUploadMultipleFiles>>,
	TError,
	{ data: FilesControllerUploadMultipleFilesBody },
	TContext
> => {
	const mutationKey = ["filesControllerUploadMultipleFiles"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof filesControllerUploadMultipleFiles>>,
		{ data: FilesControllerUploadMultipleFilesBody }
	> = (props) => {
		const { data } = props ?? {};

		return filesControllerUploadMultipleFiles(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type FilesControllerUploadMultipleFilesMutationResult = NonNullable<
	Awaited<ReturnType<typeof filesControllerUploadMultipleFiles>>
>;
export type FilesControllerUploadMultipleFilesMutationBody =
	FilesControllerUploadMultipleFilesBody;
export type FilesControllerUploadMultipleFilesMutationError = void;

/**
 * @summary Upload multiple files at once
 */
export const useFilesControllerUploadMultipleFiles = <
	TError = void,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof filesControllerUploadMultipleFiles>>,
			TError,
			{ data: FilesControllerUploadMultipleFilesBody },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof filesControllerUploadMultipleFiles>>,
	TError,
	{ data: FilesControllerUploadMultipleFilesBody },
	TContext
> => {
	return useMutation(
		getFilesControllerUploadMultipleFilesMutationOptions(options),
		queryClient,
	);
};
/**
 * Mark a list of files as completed/committed.
 * @summary Confirm files (mark as completed)
 */
export type filesControllerConfirmFilesResponse200 = {
	data: void;
	status: 200;
};

export type filesControllerConfirmFilesResponseSuccess =
	filesControllerConfirmFilesResponse200 & {
		headers: Headers;
	};

export type filesControllerConfirmFilesResponse =
	filesControllerConfirmFilesResponseSuccess;

export const getFilesControllerConfirmFilesUrl = () => {
	return `/files/confirm`;
};

export const filesControllerConfirmFiles = async (
	filesControllerConfirmFilesBody: FilesControllerConfirmFilesBody,
	options?: RequestInit,
): Promise<filesControllerConfirmFilesResponse> => {
	return HttpClient<filesControllerConfirmFilesResponse>(
		getFilesControllerConfirmFilesUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(filesControllerConfirmFilesBody),
		},
	);
};

export const getFilesControllerConfirmFilesMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof filesControllerConfirmFiles>>,
		TError,
		{ data: FilesControllerConfirmFilesBody },
		TContext
	>;
	request?: SecondParameter<typeof HttpClient>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof filesControllerConfirmFiles>>,
	TError,
	{ data: FilesControllerConfirmFilesBody },
	TContext
> => {
	const mutationKey = ["filesControllerConfirmFiles"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof filesControllerConfirmFiles>>,
		{ data: FilesControllerConfirmFilesBody }
	> = (props) => {
		const { data } = props ?? {};

		return filesControllerConfirmFiles(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type FilesControllerConfirmFilesMutationResult = NonNullable<
	Awaited<ReturnType<typeof filesControllerConfirmFiles>>
>;
export type FilesControllerConfirmFilesMutationBody =
	FilesControllerConfirmFilesBody;
export type FilesControllerConfirmFilesMutationError = unknown;

/**
 * @summary Confirm files (mark as completed)
 */
export const useFilesControllerConfirmFiles = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof filesControllerConfirmFiles>>,
			TError,
			{ data: FilesControllerConfirmFilesBody },
			TContext
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof filesControllerConfirmFiles>>,
	TError,
	{ data: FilesControllerConfirmFilesBody },
	TContext
> => {
	return useMutation(
		getFilesControllerConfirmFilesMutationOptions(options),
		queryClient,
	);
};
/**
 * Retrieve file metadata for a specific file. User-scoped - users can only access their own files.
 * @summary Get file metadata by ID
 */
export type filesControllerGetFileResponse200 = {
	data: FilesControllerGetFile200;
	status: 200;
};

export type filesControllerGetFileResponse404 = {
	data: void;
	status: 404;
};

export type filesControllerGetFileResponseSuccess =
	filesControllerGetFileResponse200 & {
		headers: Headers;
	};
export type filesControllerGetFileResponseError =
	filesControllerGetFileResponse404 & {
		headers: Headers;
	};

export type filesControllerGetFileResponse =
	| filesControllerGetFileResponseSuccess
	| filesControllerGetFileResponseError;

export const getFilesControllerGetFileUrl = (id: string) => {
	return `/files/${id}`;
};

export const filesControllerGetFile = async (
	id: string,
	options?: RequestInit,
): Promise<filesControllerGetFileResponse> => {
	return HttpClient<filesControllerGetFileResponse>(
		getFilesControllerGetFileUrl(id),
		{
			...options,
			method: "GET",
		},
	);
};

export const getFilesControllerGetFileQueryKey = (id: string) => {
	return [`/files/${id}`] as const;
};

export const getFilesControllerGetFileQueryOptions = <
	TData = Awaited<ReturnType<typeof filesControllerGetFile>>,
	TError = void,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof filesControllerGetFile>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getFilesControllerGetFileQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof filesControllerGetFile>>
	> = ({ signal }) => filesControllerGetFile(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof filesControllerGetFile>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FilesControllerGetFileQueryResult = NonNullable<
	Awaited<ReturnType<typeof filesControllerGetFile>>
>;
export type FilesControllerGetFileQueryError = void;

export function useFilesControllerGetFile<
	TData = Awaited<ReturnType<typeof filesControllerGetFile>>,
	TError = void,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof filesControllerGetFile>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof filesControllerGetFile>>,
					TError,
					Awaited<ReturnType<typeof filesControllerGetFile>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerGetFile<
	TData = Awaited<ReturnType<typeof filesControllerGetFile>>,
	TError = void,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof filesControllerGetFile>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof filesControllerGetFile>>,
					TError,
					Awaited<ReturnType<typeof filesControllerGetFile>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerGetFile<
	TData = Awaited<ReturnType<typeof filesControllerGetFile>>,
	TError = void,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof filesControllerGetFile>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get file metadata by ID
 */

export function useFilesControllerGetFile<
	TData = Awaited<ReturnType<typeof filesControllerGetFile>>,
	TError = void,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof filesControllerGetFile>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getFilesControllerGetFileQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve all files uploaded by the authenticated user, ordered by creation date (newest first).
 * @summary List all files for a user
 */
export type filesControllerListFilesResponse200 = {
	data: FilesControllerListFiles200Item[];
	status: 200;
};

export type filesControllerListFilesResponseSuccess =
	filesControllerListFilesResponse200 & {
		headers: Headers;
	};

export type filesControllerListFilesResponse =
	filesControllerListFilesResponseSuccess;

export const getFilesControllerListFilesUrl = () => {
	return `/files`;
};

export const filesControllerListFiles = async (
	options?: RequestInit,
): Promise<filesControllerListFilesResponse> => {
	return HttpClient<filesControllerListFilesResponse>(
		getFilesControllerListFilesUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getFilesControllerListFilesQueryKey = () => {
	return [`/files`] as const;
};

export const getFilesControllerListFilesQueryOptions = <
	TData = Awaited<ReturnType<typeof filesControllerListFiles>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof filesControllerListFiles>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof HttpClient>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getFilesControllerListFilesQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof filesControllerListFiles>>
	> = ({ signal }) => filesControllerListFiles({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof filesControllerListFiles>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FilesControllerListFilesQueryResult = NonNullable<
	Awaited<ReturnType<typeof filesControllerListFiles>>
>;
export type FilesControllerListFilesQueryError = unknown;

export function useFilesControllerListFiles<
	TData = Awaited<ReturnType<typeof filesControllerListFiles>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof filesControllerListFiles>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof filesControllerListFiles>>,
					TError,
					Awaited<ReturnType<typeof filesControllerListFiles>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerListFiles<
	TData = Awaited<ReturnType<typeof filesControllerListFiles>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof filesControllerListFiles>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof filesControllerListFiles>>,
					TError,
					Awaited<ReturnType<typeof filesControllerListFiles>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerListFiles<
	TData = Awaited<ReturnType<typeof filesControllerListFiles>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof filesControllerListFiles>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all files for a user
 */

export function useFilesControllerListFiles<
	TData = Awaited<ReturnType<typeof filesControllerListFiles>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof filesControllerListFiles>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof HttpClient>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getFilesControllerListFilesQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
